### ISSUE TITLE
State feature: Timeout

### ISSUE THREAD

**Issue by aleneum** [pytransitions/transitions#229]
Adds the ability to timeout an entered state. See: [states.py](https://github.com/pytransitions/transitions/blob/dev-state-extensions/transitions/extensions/states.py#L35)

### Keywords

* `timeout` (int, optional) -- if passed, an entered state will timeout after `timeout` seconds
* `on_timeout` (string/callable, optional) -- will be called when timeout time has been reached

### Exceptions:
  - will raise an `AttributeError` when `timeout` is set but `on_timeout` is not

### Example Usage

```python
from transitions import Machine
from transitions.extensions.states import add_state_features, Timeout

import time


@add_state_features(Timeout)
class CustomMachine(Machine):
    pass


class Model(object):

    def timeout(self):
        print("Timeout!")
        self.to_A()

model = Model()

states = ['A',
          {'name': 'B', 'timeout': 0.3, 'on_timeout': 'timeout'},
          {'name': 'C', 'timeout': 0.9, 'on_timeout': model.timeout}]

m = CustomMachine(model, states=states, initial='A')
model.to_B()
time.sleep(1)  # >>> "Timeout!"
print model.state  # >>>  'A'
```

### Remark

This implementation is not thread-safe! The user may either lock the model or use `LockedMachine`.

**Comment by Synss** [comment]
Hi, great to see this coming. Just two small things: could you put a comment to #198: I was following #198 and overlooked this thread until yesterday. I would also check the presence of `on_timeout` with [EAFP](https://docs.python.org/2/glossary.html#term-eafp)

```diff --git a/transitions/extensions/states.py b/transitions/extensions/states.py
index 40e9ce7..1d8a01f 100644
--- a/transitions/extensions/states.py
+++ b/transitions/extensions/states.py
@@ -36,8 +36,9 @@ class Timeout(object):
     def __init__(self, *args, **kwargs):
         self.timeout = kwargs.pop('timeout', 0)
         if self.timeout > 0:
-            self.on_timeout = kwargs.pop('on_timeout', None)
-            if self.on_timeout is None:
+            try:
+                self.on_timeout = kwargs["on_timeout"]
+            except KeyError as exc:
                 raise AttributeError("Timeout state requires 'on_timeout' when timeout is set.")
         self.runner = {}
         super(Timeout, self).__init__(*args, **kwargs)
```

This way, you avoid the ``if`` in the normal case.

**Comment by aleneum** [comment]
Hi @Synss, 

thank you for the feedback. Just a remark why I sticked with `kwargs.pop`:  The `add_state_feature` decorator will add mixins to the state class of the chosen `Machine`. `State` does not handle `*args` or `**kwargs` which means that eventually all custom arguments have to be 'consumed'. The required mixin style becomes a bit stricter but should make bug tracking easier when keywords have been accidentally used twice or a mixin 'misbehaves'.

**Comment by Synss** [comment]
Servus! Thank you for your quick answer and for taking my patch. That is really appreciated.

If ever you want a pedantic code review either now or when you go 3+-only, do not hesitate to ask: I can do that in my paid-for time ;-)

**Comment by Synss** [comment]
``Machine.add_states()`` could accept ``*args, **kwargs`` so that ``Machine.add_state("A", timeout=999, on_timeout=lambda: None)`` work.

I can make a pull request if you agree with the idea.

**Comment by aleneum** [comment]
Good point,

`HierarchicalStateMachine.add_states` can already handle that. What do you think about accepting just `**kwargs` here? This way state parameters have to be passed as keyword arguments. Passing them as ordered arguments feels like a futile endeavor to me. Actually, the state mixins could not handle `*args` anyway.

**Comment by Synss** [comment]
I have changed my mind since #237, I now believe that listifying `on_timeout` and allowing to `add_callback("timeout", ...)` would be useful.

That would allow me to remove the `timeout_error` state in the following case:
```
state -[timeout]-> timeout_error [do/ write error message] --> error
```
and instead to have two `on_timeout` callbacks, one writing the error message and the second one transitioning to `error`.
```
state -[timeout, write error message]-> error
```

Have you started working on this?

**Comment by aleneum** [comment]
> Have you started working on this?

has been implemented and [tested](https://github.com/pytransitions/transitions/blob/dev-state-extensions/tests/test_states.py#L82). Hope this enables your workflow.
