### ISSUE TITLE
Move pygraphviz to `extras_require`

### ISSUE THREAD

**Issue by aleneum** [pytransitions/transitions#233]
This makes installing transitions easier for users of platforms where pygraphviz is known to have issues (I am looking at you, Windows!). The drawback is that everyone else has to *specifically* install transitions with

```bash
pip install transitions[diagrams]
```

Opinions?

**Comment by ankostis** [comment]
(sorry to provide feedback so late)
Have you considered environmental markers?
http://setuptools.readthedocs.io/en/latest/setuptools.html#id15

**Comment by aleneum** [comment]
Hi @ankostis,

> (sorry to provide feedback so late)
feedback is always appreciated.

> Have you considered environmental markers?

not yet. I guess you suggest to make `pygraphviz` a dependency for *nix systems only, right?

My motivation to make `pygraphviz` optional is that it is actually optional. You even extended the tests to skip pygraphviz related tests :). I'd love if setuptools/pip had some 'default enabled' optional handling like homebrew (`--no-pygraphviz`). But I am not aware of any solution like that.

Do you see issues with making `diagrams` and optional feature?

**Comment by ankostis** [comment]
You can also add [environment-markers for `extras`](https://www.python.org/dev/peps/pep-0508/):
```python
extras_require={
            'diagrams:sys_platform != "win32"': 'pygraphviz >= x.y.z')
}
```

**Comment by aleneum** [comment]
Okay, good to know but I would like to avoid platform dependent behaviour.
Except if there is a good reason why making `diagrams` optional for everyone might be a bad idea.

**Comment by ankostis** [comment]
I agree that it `diagrams` should be an optional extras - I consider diagrams an "interactive" feature that is a waste of space for headless or unsupervised applications that depend on your library.

And using environment-markers for platform dependent behaviour is obligatory on "wheels", where the `setup.py` script is never executed.

**Comment by aleneum** [comment]
> And using environment-markers for platform dependent behaviour is obligatory on "wheels", where the setup.py script is never executed.

I see. Thanks for bringing environment markers to my attention. Knowing about this feature and its purpose will defo save some time in the future.

Do you have positive experience with certain `pygraphviz` versions under Windows or know some versions which definitely won't work?

**Comment by ankostis** [comment]
No I have not.
6 months ago I hadn't managed to install this library - we use [`graphviz` lib](https://pypi.python.org/pypi/graphviz) instead.
