### ISSUE TITLE
Instantiating HSM with list of State objects fails

### ISSUE THREAD

**Issue by Blindfreddy** [pytransitions/transitions#238]
Hi 

I believe I have found a bug in the HSM: instantiating HSM with a liste of State objects fails, whereas instantiating it with a list of dictionaries works fine. Also, instantiating a normal, non hierarchical Machine with a list of State objects works.

Steps to reproduce:

Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from transitions import Machine
>>> from transitions import State
>>> d = {'name' : 'On', 'on_enter' : '_activate'}
>>> s = State(**d)
>>> l=[s]
>>> m = Machine('self', l)
>>> m.states
OrderedDict([('On', <State('On')@3064243984>), ('initial', <State('initial')@3064243856>)])
>>> m = Machine('self', [d])

The code above works fine with both a list of State objects as well as a list of dictionaries.

Now, if we do likewise with HSM it only works with a list of dictionaries but raises an exception with list of State objects:

OK with list of dictionaries:

>>> from transitions.extensions import HierarchicalMachine as Machine
>>> m = Machine('self', [d])
>>> m.states
OrderedDict([('On', <NestedState('On')@3062594000>), ('initial', <NestedState('initial')@3062593072>)])

But when the HSM is created with a list of State objects it fails;

>>> m = Machine('self', l)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/transitions/extensions/nesting.py", line 164, in __init__
    super(HierarchicalMachine, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/transitions/core.py", line 448, in __init__
    self.add_states(states)
  File "/usr/local/lib/python3.4/dist-packages/transitions/extensions/nesting.py", line 295, in add_states
    new_states = self.traverse(states, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/transitions/extensions/nesting.py", line 281, in traverse
    raise ValueError("%s cannot be added to the machine since its type is not known." % state)
ValueError: <State('On')@3064243984> cannot be added to the machine since its type is not known.
>>>

**Comment by aleneum** [comment]
Hi @Blindfreddy,

if you could provide a minimal example where this error occurs, I will start investigating (and hopefully fixing it) right away.

**Comment by aleneum** [comment]
Well, I guess I see the issue. You try to add `State` objects to a `HierarchicalMachine` which requires `NestedState` as a state type. The error message should mention that more precisely.

**Comment by Blindfreddy** [comment]
Yes, a more precise error message would be useful.  Perhaps also mention it in the HSM section of the documentation, including different imports (if any).

**Comment by aleneum** [comment]
In `0.6`, we will introduce a *MixIn* workflow for extending states which should make customizing states easier. The [ReadMe](https://github.com/pytransitions/transitions/blob/dev-state-extensions/README.md) of the dev-branch already contains more details about how this process should look like. I extended it by an example about how 'standard' subclassing could look like.
