### ISSUE TITLE
model not None but False

### ISSUE THREAD

**Issue by booware** [pytransitions/transitions#240]
Hello,
I would like to make a suggestion, in transitions/core.py:

in **Machine.__init__**, I think that:

`if model and initial is None:` (line 442) should be `if model is not None and initial is None:`

`if model:` (line 475) should be `if model is not None:`

I had troubles with a class extending abstract collections (sequence, mapping...) because unexpected behaviour is obtained if the collection is empty (and the same for any class implementing __bool__ as well).

thanks

**Comment by tyarkoni** [comment]
At first glance, this makes sense to me. Do you want to open a PR for those changes, @booware?

**Comment by aleneum** [comment]
Just realised there is a problem. The test `test_add_model_no_initial_state` actually expects `[]` to be handled as no model. This was implented by @paulbovbel and its probably intentional.

**Comment by booware** [comment]
this absolutely makes sense since the add_model method can take a sequence as 'model' argument, but I think this should be documented about Machine initialization

**Comment by booware** [comment]
Sorry just realized it actually is, am I just not careful enough or maybe this should be a bit more explicit or an example should be added in the documentation ? 

the Machine.__init__ doc says : 

> model (object): The object(s) whose states we want to manage. If 'self',
                the current Machine instance will be used the model (i.e., all
                triggering events will be attached to the Machine itself).

**Comment by aleneum** [comment]
you are right, the docstring isn't accurate. I extended it accordingly.

 > example should be added in the documentation ?

In the [alternative initialization pattern section](https://github.com/pytransitions/transitions#alternative-initialization-patterns) you will find the following passage:

> A machine can handle multiple models which can be passed as a list like Machine(model=[model1, model2, ...]). In cases where you want to add models as well as the machine instance itself, you can pass the string placeholder 'self' during initialization like Machine(model=['self', model1, ...])

Do you think this is sufficient or do you have any suggestions how to extend this section?

If you have any other idea about making the model parameter a bit more versatile (without extensive type checks ;)), let us know.

**Comment by booware** [comment]
thank you, I didn't see this part in the documentation, seems pretty clear to me, the thing is you don't necessarily go through it if you don't intend to initialize with several models so basically you don't know 'model' can be interpreted as 'models', but my thought is it's ok if it's clear in the __init__ doc...

Maybe this is a personal feeling but I would find more intuitive to use 'model**s**' keyword in arguments instead of 'model' given the fact you can have one or more, and used 'add_model**s**' instead of 'add_model' in the same way

**Comment by paulbovbel** [comment]
The `listify` behaviour is super handy, but a bit magical and not always obvious. This is exacerbated by the dillema of Python's false-y evaluation of empty lists, and the expectation that you could hypothetically use a `list`/`dict`/etc. as a model (because why not?).

A split in the API such as add_model and add_models may help to clarify the distinction.

Without breaking API, it might be helpful to have API docs generated of the package, where the contract of the API, and the input parameters, is more clearly laid out for consumption.

**Comment by aleneum** [comment]
API documentation has been added for (at least) every public method. I close this issue for now. Feel free to comment if you consider this issue as not being solved by the documentation attempt or open a new issue if you have further recommendations about how to improve transitions documentation.
