### ISSUE TITLE
NestedState callbacks don't seem to be called in nested states

### ISSUE THREAD

**Issue by Blindfreddy** [pytransitions/transitions#243]
Hi

Not sure if this is a feature of a bug but it seems that callbacks on_enter and on_exit are not called in nested states unless explicitly added using on_enter() / on_exit()

Steps to reproduce:

Extend the example in the HSM documentation by adding callbacks 'on_enter' to the state definitions and add a couple of transitions to make the callbacks fire:

```python
from transitions.extensions import HierarchicalMachine as Machine
from transitions.extensions.nesting import NestedState
NestedState.separator = '↦'
states = [{'name' : 'A', 'on_enter' : '_activate'}, {'name' : 'B', 'on_enter' : '_deactivate'},
          {'name': 'C', 'on_enter' : 'ac1', 'children':
              ['1', '2', {'name': '3', 'children': ['a', 'b', 'c']}]}]

transitions = [
    ['reset', 'C', 'A'],
    ['b', '*', 'B'],
    ['c', '*', 'C'],
    ['reset', 'C↦2', 'C']  # overwriting parent reset
]

# Define a simple model:
class MC(object):

    def _activate(self):
        print('Activating....')
    
    def _deactivate(self):
        print('Deactivating....')
    
    def _power_auto(self):
        print('_power_auto')
            
    def ac1(self):
        print('ac1')

mc = MC()
# Instantiate a machine
machine = Machine(model=mc, states=states, transitions=transitions, initial='A')
m.b()  # >>> Deactivating....
m.c()  # Nothing... should be 'acc1'
m.reset()  # >>> Activating....
```

Note that the expected callback 'ac1' was not called !!!!
Callback for non-nested state was called.

**Comment by Blindfreddy** [comment]
apologies for not properly marking the code - it's beyond me to format it in this editor....

**Comment by aleneum** [comment]
Hi @Blindfreddy,

> Note that the expected callback 'ac1' was not called !!!!

this has been a bug in the way how NestedStates are recursively initialised. It should not be necessary to explicitly assign the callback. Unfortunately, test had only covered this manual approach so far.

Thanks for taking the time to write a bug report. I reformatted your code example to be directly executable with copy/paste. Give it a try. It should work now.

**Comment by Blindfreddy** [comment]
Ok thanks, appreciate the reformatting.

Also, I found a workaround:  instantiate NestedState objects using, in the case of children with the `parent=` keyword argument, jointly with `on_enter=` and/or `on_exit=` . Subsequently instantiate the machine using the list of NestedState objects, all callbacks are then called.

**Comment by aleneum** [comment]
jupp, its the way the dictionary had been traversed. Initializing instances of `NestedState` directly has not been influenced.
