### ISSUE TITLE
Wait for multiple events before transition from single state possible?

### ISSUE THREAD

**Issue by bedge** [pytransitions/transitions#247]
I need to wait for 3 things to happen before I transition to the next state.

State = `WAIT_FOR_3_THINGS`
Events = `thing_1_done, thing_2_done, thing_3_done`

The thing_*_events can come in any order, so I'd prefer to avoid having a:

`thing_1_and_2_done, thing_1_and_3_done, thing_2_and_3_done` states

I can track events, 1, 2, & 3 and advance with a 
`conditions=[thing_1_and_2_done, thing_1_and_3_done, thing_2_and_3_done]`
but I'm not sure where best to aggregate these event occurences.

Is there a more skookum (ok, pythonic) way of doing this?

**Comment by bedge** [comment]
I'm going with a condition:
```
    def if_rundeps_ready(self, event):
        return self.run_deps == RunDeps.READY
```
that I init in the FSM constructor:
```
self.rundeps = RunDeps.INIT
```

with an bitmask enum:
```
class Rundeps(Enum):

    INIT = 0
    THING_1 = 1
    THING_2 = 2
    THING_3 = 4
    READY = THING_1 + THING_2 + THING_3
```
and remain in the same event until READY.

Still interested to hear other options.

**Comment by aleneum** [comment]
This sounds like something very suited for Stackoverflow. I quote myself from the past:

> This has several advantages:
> * Your question gains higher visibility since most developers look for help there
> * The targeted community is larger; Some people will even help you to formulate a good question
> * People get 'rewarded' with 'reputation' to help you. You also gain reputation in case this questions pops up more frequently. It's a win-win situation.

Eventually it also helps to grow the `transitions` community since SO produces some decent incoming traffic.

**Comment by bedge** [comment]
xposted to S.O. https://stackoverflow.com/questions/45515392/python-transitions-lib-wait-for-multiple-events-before-transition-from-single

**Comment by bedge** [comment]
Resolving, details on S.O. at above link. Better options probably exist, but it works and doesn't completely suck.
