### ISSUE TITLE
`get_triggers` doesn't check conditions

### ISSUE THREAD

**Issue by benselme** [pytransitions/transitions#256]
`Machine.get_triggers` doesn't check conditions, and so returns triggers that can't actually be called.

Generally, there is no mechanism to check upon a transition's conditions before actually trying to apply it.

**Comment by aleneum** [comment]
Hello @benselme,

> Machine.get_triggers doesn't check conditions, and so returns triggers that can't actually be called.

correct. `Machine.get_triggers` only evaluates events and checks where the passed state is the source state. This means, it returns *theoretically* possible transitions but not the transitions possible at the current point in time.

> Generally, there is no mechanism to check upon a transition's conditions before actually trying to apply it.

So you are looking for a way to 'peek' into these transitions and test whether *prepare* and *conditions* callbacks will be executed successfully? If so: yes, there is not way to *attempt* to execute a transition without actually executing it.

Could you elaborate on your use case or clarify what you would suggest as a desirable feature?

**Comment by benselme** [comment]
I'm trying to answer the question, "Where can I go from here ?". For example I might want to disable certain UI controls that would trigger an impossible transition. Something similar to [django-fsm](https://github.com/kmmbvnr/django-fsm)'s `can_proceed`.

Something like this should do the trick I guess:

        def can_trigger(self, trigger_name):
            return trigger_name in self.get_triggers(self.state) and any(
                all(c.check() for c in t.conditions)
                for t in self.events[trigger_name].transitions.items())

**Comment by aleneum** [comment]
Hi @benselme,

`EventData` is a collection of data relevant for the transition which you can create on the fly as you can see in the following example. `PeekMachine` is based on your initial idea (thanks for that) and adds a `can_trigger` method to each model for convenience.

```python
from transitions import Machine, EventData
from functools import partial


class Model(object):

    def fails(self, condition=False):
        return False

    def success(self, condition=False):
        return True

    # condition is passed by EventData
    def depends_on(self, condition=False):
        return condition

    def is_state_B(self, condition=False):
        return self.state == 'B'


class PeekMachine(Machine):

    def _can_trigger(self, model, *args, **kwargs):
        e = EventData(model.state, None, self, model, args, kwargs)

        return [trigger_name for trigger_name in self.get_triggers(model.state)
                if any(all(c.check(e) for c in t.conditions)
                       for ts in self.events[trigger_name].transitions.values()
                       for t in ts)]

    # override Machine.add_model to assign 'can_trigger' to the model
    def add_model(self, model, initial=None):
        super(PeekMachine, self).add_model(model, initial)
        setattr(model, 'can_trigger', partial(self._can_trigger, model))


states = ['A', 'B', 'C', 'D']
transitions = [
    dict(trigger='go_A', source='*', dest='A', conditions=['depends_on']),  # only available when condition=True is passed
    dict(trigger='go_B', source='*', dest='B', conditions=['success']),  # always available
    dict(trigger='go_C', source='*', dest='C', conditions=['fails']),  # never available
    dict(trigger='go_D', source='*', dest='D', conditions=['is_state_B']),  # only available in state B
    dict(trigger='reset', source='D', dest='A', conditions=['success', 'depends_on']), # only available in state D when condition=True is passed
    dict(trigger='forwards', source='A', dest='D', conditions=['success', 'fails']),  # never available
]

model = Model()
machine = PeekMachine(model, states=states, transitions=transitions, initial='A', auto_transitions=False)
assert model.can_trigger() == ['go_B']
assert model.can_trigger(condition=True) == ['go_A', 'go_B']
model.go_B(condition=True)
assert model.can_trigger() == ['go_B', 'go_D']
model.go_D()
assert model.can_trigger() == ['go_B']
assert model.can_trigger(condition=True) == ['go_A', 'go_B', 'reset']
```

**Comment by benselme** [comment]
Yes, that's exactly what I was looking for. Thanks.

**Comment by aleneum** [comment]
Currently this does not seem an urgent feature request but should definitely be documented in case other users may stumble upon the same issue. The presented solution will be documented in the example section.

**Comment by daino3** [comment]
FWIW - I also expected the library to have this functionality. It's immensely useful for having FSM logic server-side and serializing possible transitions for a client (e.g. UI). That way, you don't need to reinvent a FSM in two places.

**Comment by lortiz-nativo** [comment]
This thread is a little old now but I found the solution that @aleneum gave to be very helpful for my use case and I wanted to point out a small problem i ran into. The can_trigger function will return triggers that are not valid if they share the same name as valid triggers from a different source state. These should not be taken into account since we know what our current state is.

I think these transitions will reveal the error. If our model is in state B can_trigger will still return go_A even though the successful transition does not apply because it required source A.
```
transitions = [
    dict(trigger='go_A', source='B', dest='A', conditions=['fails']),
    dict(trigger='go_A', source='C', dest='A', conditions=['success']),
]
```

I think this should fix it

    def _can_trigger(self, model, *args, **kwargs):
        # We can omit the first two arguments state and event since they are only needed for
        # actual state transitions. We do have to pass the machine (self) and the model as well as
        # args and kwargs meant for the callbacks.
        e = EventData(None, None, self, model, args, kwargs)

        return [
            trigger_name
            for trigger_name in self.get_triggers(model.state)
            if any(
                all(c.check(e) for c in t.conditions)
                for t in self.events[trigger_name].transitions[model.state]
            )
        ]

**Comment by FridjofAmundsen** [comment]
@lortiz-nativo @aleneum thanks for your solution, unfortunately it doesn't work with nested machines.

But I figured it out for Hierarchical machines. Here is the solution:

'''python
    def can_trigger(self, trigger_name, *args, **kwargs):
        """
        checks whether a transition can be triggered from the current state.
        Parameters
        ----------
        trigger_name : the trigger name
        args : past to the Event()
        kwargs :  past to the Event()

        Returns whether a transition can be triggered from the current state.
        -------

        """

        cur_state = self.model.state

        pos_trigs = self.get_triggers(cur_state)
        if trigger_name not in pos_trigs:
            return False

        # print('_stac: ', len(self._stack))
        _stack = self._stack
        nested_states = cur_state.split(self.state_cls.separator)

        dest_machine = None  # destination machine
        source_events = None  # events from the source machine

        # find the correct machine and events
        if trigger_name in self.events:
            dest_machine = self
            source_events = dest_machine.events
        # if it is a nested state it is different
        if _stack and len(nested_states) > 1:
            s = _stack[-1]
            scoped, states, source_events, prefix_path = s
            ns_2 = nested_states[:-1]
            parent_state = self.state_cls.separator.join(ns_2)
            if parent_state in states:
                ps = states[parent_state]
                if trigger_name in ps.events:  # transition inside nested machine
                    e = ps.events[trigger_name]
                    dest_machine = e.machine
                    source_events = dest_machine.events
                elif trigger_name in source_events.keys():  # transition into parent machine
                    se = scoped.events.values()
                    if se:
                        dest_machine = se[0].machine  # destination machine
                        # source_events need to be from the inner machine
        if not dest_machine:
            print('error in can_trigger trigger_name: ', trigger_name)
            return False
'''

**Comment by aleneum** [comment]
Just FYI: Starting with `0.9.0` transitions support [may_<trigger>](https://github.com/pytransitions/transitions#check-transitions). This might be helpful in some cases.
