### ISSUE TITLE
How not to use "magic strings" as identifiers for state machine

### ISSUE THREAD

**Issue by nakiya** [pytransitions/transitions#261]
I plan to use this package in the project I'm starting. However, I have a simple concern. Usually, it's a good idea to use a named constant for the string. However, going this route with the transitions package seems to be problematic. Simplified example:

```
class StateMachineModel:

    STATENAME_INITIAL = 'initial'
    STATENAME_REPORT = 'report'

    TRANSITIONNAME_CREATE_REPORT = 'create_report'
    TRANSITIONNAME_HAS_ERRORS = 'has_errors'

   STATES = [
        State(STATENAME_INITIAL,
              on_enter='on_enter_initial',
              on_exit='on_exit_initial'),
        State(STATENAME_REPORT,
              on_enter='on_enter_report',
              on_exit='on_exit_report'),
   ]

    TRANSITIONS = [
        {'trigger': TRANSITIONNAME_CREATE_REPORT,
         'source': STATENAME_INITIAL,
         'dest': STATENAME_REPORT,
         'conditions': 'has_permission'},
        {'trigger': TRANSITIONNAME_HAS_ERRORS,
         'source': STATENAME_REPORT,
         'dest': STATENAME_REPORT,
         'conditions': ['has_permission'],
         'after': ['on_errors_in_report']},
    ]
 
...

    machine = Machine(model=model, states=StateMachineModel.STATES,
                      transitions=StateMachineModel.TRANSITIONS,
                      send_event=True,
                      initial=StateMachineModel.STATENAME_INITIAL)
```

Now, I have to call `model.create_report` to transition from `initial` to `report` state. Which seems to me to defeat the whole purpose of defining state and transition names with constants. (i.e. `STATENAME_INITIAL = 'initial'`). So later, if I were to change any of these transition names (or `conditions`, `after`, etc) I'd have to search for these strings in code to see if there's any method name by the same string used.

Is there anything that can be done about this problem?

**Comment by aleneum** [comment]
Hello @nakiya,

if you want to use constants to name states you can use the feature mentioned in the documentation here:

> Additionally, there is a method called trigger now attached to your model. This method lets you execute transitions by name in case dynamic triggering is required.

```python
model.trigger(TRANSITIONNAME_CREATE_REPORT, *args, **kwargs)
```
This is more or less equivalent to calling

```python
getattr(model, TRANSITIONNAME_CREATE_REPORT)(*args, **kwargs)
```

You might want to reconsider your naming for `on_enter/exit` callbacks as well since `on_enter_initial` might become confusing in case you change `STATENAME_INITIAL`. Of course you could also just use `STATENAME_INITIAL` there as well:

```python
State(STATENAME_INITIAL,
      on_enter='on_enter_{0}'.format(STATENAME_INITIAL),
      on_exit='on_exit_{0}'.format(STATENAME_INITIAL)),
#...
```

**Comment by aleneum** [comment]
I close this due to inactivity. If you still think there is an issue with `transitions` which should be resolved. Feel free to comment and I will reopen the issue if necessary.
