### ISSUE TITLE
Graph callbacks as actions

### ISSUE THREAD

**Issue by bengartner** [pytransitions/transitions#264]
Would like to see enter, exit labeled as entry and exit in a node. Would also like to see after/before actions with a / notation. Not sure how to best represent prepare actions as they don't seem to fit into standard UML notation per my understanding.

I can but this in a PR if it's likely to go in, if not I'll just add in my project.

**Comment by aleneum** [comment]
Hello @bengartner,

pull requests are always appreciated and we are grateful for every community member who strives for improving `transitions`. Whether a pull request is accepted depends on several factors. For instance:

* required change of the current codebase
* impact on usage complexity
* impact on maintainability of `transitions`
* impact on default behaviour
* community feedback

I cannot really tell you if a PR is accepted before reviewing it and/or getting feedback of other users. Let's keep this issue open and see what others think about this feature.

**Comment by bengartner** [comment]
Okay - I think I can put it in without changing default behavior or adding too much code. Just wanted to check if there was already discussion I'd missed. I'll fork for now and put up a PR after waiting for some feedback.

Here's an [example of the slash notation] (https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/UML_state_machine_Fig7.png/660px-UML_state_machine_Fig7.png) from wikipedia's [UML state machine](https://en.wikipedia.org/wiki/UML_state_machine).

There's already code for optionally displaying transition conditions in []s so it should be easy enough to add to the transitions. Nodes use a default for the label so I'll have to add an analogous function there.

Or I could do something that's a little more flexible in terms of how labels are generated, IE an internal function that can generically map graphing attributes, but it seems premature for that. Not sure how much flexibility is actually needed - or what people want other than standard UML stuff.

UML seems to treat all transition actions the same, so I can incorporate any advice on how transitions treats them - I tend to avoid using more than one action on the same transition.

**Comment by aleneum** [comment]
Hello @bengartner,

are there any updates for this issue? Did you manage to rework graphs to get closer to UML standards?

**Comment by aleneum** [comment]
closing due to lack of feedback. If this issue becomes valid again, comment and I will reopen it.
