### ISSUE TITLE
Which Model ?

### ISSUE THREAD

**Issue by qkmaosjtu** [pytransitions/transitions#270]
```
m = Model()
# in cases where auto transitions should be visible
# Machine(model=m, show_auto_transitions=True, ...)

# draw the whole graph ...
m.get_graph().draw('my_state_diagram.png', prog='dot')
# ... or just the region of interest
# (previous state, active state and all reachable states)
m.get_graph(show_roi=True).draw('my_state_diagram.png', prog='dot')
```
What extra dependecy  should I add for Model()?

**Comment by aleneum** [comment]
Hello @qkmaosjtu,

`Model` is your model object which is enhanced by `transitions` and changes state whenever an operation is conducted. In the ReadMe the `NarcolepticSuperhero` is a model or `Matter`. The most simple possible model is:

```python
class Model:
    pass
```

**Comment by aleneum** [comment]
closed due to inactivity. Feel free to comment in case you think this issue hasnt been solved. I will reopen the issue if required.
