### ISSUE TITLE
Linking two machines together

### ISSUE THREAD

**Issue by avneesh91** [pytransitions/transitions#271]
Hi,

I need to compile a list of very large workflows writing them individually will be too much in terms of manual effort.

Though the flows are large, but are relatively simple. They are just different  combinations of smaller workflows.

Is there a possibility that I can write small machines and combine them together in different permutations and combinations for all my different flows?

Thanks,
Avneesh

**Comment by aleneum** [comment]
Hello @avneesh91,

this might be what you are looking for: https://github.com/pytransitions/transitions#reuse-of-previously-created-hsms
