### ISSUE TITLE
Add new states to NestedState at runtime

### ISSUE THREAD

**Issue by hrsmanian** [pytransitions/transitions#275]
Hi,
  Is it possible to add new states to a NestedState at runtime? The code snippet below doesn't work.
Basically I want to add a state '4' as a child of state '2'. I get an attribute error like
AttributeError: 'str' object has no attribute 'children'. Any pointer will be very helpful

Thanks

``` python
class Foo(HMachine) :
    def __init__(self) :

        self.states = [NestedState(name='1'), {'name': '2'},
                       NestedState('3')]

        HMachine.__init__(self, states=self.states, initial='1')

foo = Foo()
foo.add_transition('process', '*', '2')
foo.process()
print(foo.state)
foo.add_states(['4'], parent='2')
```

**Comment by aleneum** [comment]
Hi @hrsmanian,

`parent` expects a `State` object. `foo.add_states(['4'], parent=foo.get_state('2'))` works.
Or as a working example:

```python
from transitions.extensions.nesting import HierarchicalMachine as HMachine
from transitions.extensions.nesting import NestedState


class Foo(HMachine):
    def __init__(self):

        self.states = [NestedState(name='1'), {'name': '2'},
                       NestedState('3')]

        HMachine.__init__(self, states=self.states, initial='1')


foo = Foo()
foo.add_transition('process', '*', '2')
foo.process()
foo.add_states(['4'], parent=foo.get_state("2"))
foo.add_transition('into', '2', '2_4')
foo.into()
assert foo.is_2(allow_substates=True)
```

**Comment by aleneum** [comment]
Thought a bit about it and I thing `foo.add_states('4', parent='2')` is a fair guess and should be natively supported as it fits the general style of `transitions` API. Your code should work now with the current `master`.

**Comment by hrsmanian** [comment]
Thanks a lot for the reply. I did realize that the parent has to be a State object. I will sync to the latest to get the updated code. Really appreciate the help

**Comment by hrsmanian** [comment]
Hi, how do we remove states from the machine dynamically? I know the state name but cannot see an API to remove the state from the machine.

**Comment by aleneum** [comment]
States are stored in an `OrderedDict`. `del machine.states[<state_name>]` is all you need to do.
