### ISSUE TITLE
Dump Graph into a Stream instead of File (Jupyter Notebook Hack)

### ISSUE THREAD

**Issue by jlandercy** [pytransitions/transitions#276]
I discovered your package yesterday and I found myself creating some FSMs meanwhile having a lot of fun.
Thank you for sharing your work it is really valuable to me.
By the way, I specially like the [*Narcoleptic Super Hero*][2] example ([coz I'm Batman][1]) in place of API documentation.

Please find bellow a small hack that I have quickly implemented for removing the need to physically dump the graph into a file before having it displayed into a notebook:

```python
import io
from IPython.display import Image, display
from transitions.extensions import GraphMachine

class MyGraphMachine(GraphMachine):
    
    def __init__(self, *args, **kwargs):
        
        # Initialize Super:
        super().__init__(*args, **kwargs)
        
    def show(self, **kwargs):
        """
        Hack for showing Graph into Jupyter Notebook without having to dump file:
        """
        # Flush Stream first:
        stream = io.BytesIO()
        # Actually Draw the Graph into the Stream:
        self.get_graph(**kwargs).draw(stream, prog='dot', format='png')
        # Display in IPython:
        display(Image(stream.getvalue()))
```

I don't know if you are interested in, and this will certainly need some adaptations before fitting your API requirements. Anyway I wanted to share it.

Best regards,

[1]: https://www.youtube.com/watch?v=YpIQQeL2ZYk
[2]: https://github.com/pytransitions/transitions#quickstart

**Comment by aleneum** [comment]
Hello @jlandercy,

thanks for sharing that. This looks indeed like the better solutions for notebooks. I will adapt our example notebooks accordingly.

**Comment by aleneum** [comment]
added to example notebooks

**Comment by jlandercy** [comment]
You are welcome, glad you updated your example. Best regards
