### ISSUE TITLE
Event-Checking 'run' Functions

### ISSUE THREAD

**Issue by carl-lindquist** [pytransitions/transitions#277]
I was wondering if there is a run functionality for states. In other words, a function which can be run automatically while in a given state. This allows the state machine to check for a specific event, and respond to it with a state transition.

I implemented my own way of doing it, but I feel like this functionality must be baked into the module somewhere.

```
# this function would be baked in somewhere
def run(self): 
        state = self.state
	if state == ‘A':
		self.run_A()

	elif state == ‘B':
		self.run_B()

# these functions would be user defined
def run_A(self): 
	event_occurred = False

	while(not event_occurred):
		if check_for_event():
			event_occurred = True

	self.A_to_B_transition_event()


# using the run functions would look like this
def main():
	while(True):
		machine.run()
```

If this is already implemented, where is the documentation on it? Is there a reason why this does not belong in transitions?

**Comment by aleneum** [comment]
Hello @carl-lindquist,

I would say there is more than one way to achieve this. For instance have a look at [this](https://stackoverflow.com/questions/47541749/state-machine-and-toggling-states-in-a-loop/47631765#47631765). I answered a related question where repeated triggering of a function is achieved by re-entering or via strategies.
