### ISSUE TITLE
NestedState does not enter on_enter function during self loop

### ISSUE THREAD

**Issue by hrsmanian** [pytransitions/transitions#278]
Hi,
  When doing a self loop on a NestedState, the on_enter function is not being called. It works well for simple State though. An example is shown below

from transitions import Machine, State, EventData
from transitions.extensions import HierarchicalMachine as HMachine

class Foo(HMachine) :
    def __init__(self) :
        states = [{'name' : '1' , 'on_enter' : self.print_state } , { 'name': '2', 'on_enter' : self.print_state }]
        HMachine.__init__(self, states=states, initial='solid', send_event=True)

    def print_state(self, event) :
        print("Inside state " + event.state.name)

foo = Foo()
print("Foo")
foo.to_1()
foo.to_2()
foo.to_2()

class Bar(Machine) :
    def __init__(self) :
        states = [{'name' : '1' , 'on_enter' : self.print_state } , { 'name': '2', 'on_enter' : self.print_state }]
        Machine.__init__(self, states=states, initial='solid', send_event=True)

    def print_state(self, event) :
        print("Inside state " + event.state.name)

bar = Bar()
print("Bar")
bar.to_1()
bar.to_2()
bar.to_2()

Output: 
Foo
Inside state 1
Inside state 2
Bar
Inside state 1
Inside state 2
Inside state 2

Notice how the print is missing for the self loop on state 2 for NestedState. Is the behavior correct?

Thanks

**Comment by aleneum** [comment]
Hello @hrsmanian,

thank you for the bug report and brining this issue to our attention. During a reflexive transition the state should indeed be exited. The only case where this should not happen is when the target state is nested into the source state.
