### ISSUE TITLE
pygraphviz is in requirements_dev.txt but needed during execution

### ISSUE THREAD

**Issue by nicain** [pytransitions/transitions#281]
Hello All,

pygraphviz is required to execute, for example,     https://github.com/pytransitions/transitions/blob/e4dbbaa8e40d86378e3df37176faed11cb9a05b1/transitions/extensions/diagrams.py#L158, but this code can be executed outside of just testing.

I suggest moving to pygraphviz requirements.txt.  Does this sound right?

**Comment by tyarkoni** [comment]
Hi @nicain,

It's not in requirements.txt because it's not required for transitions to work--but only for optional functionality. I'd be fine with adding it to an optional-dependencies.txt file it something like that, but it shouldn't go in requirements. Alternatively, we could (should) move all that stuff to setup.py and make it an install option (e.g., [full]).

**Comment by nicain** [comment]
@tyarkoni have you considered moving over to pipenv?  I am not the authority, because I am learning it myself right now, but it looks great so far.  Optional dependencies are defined as in https://github.com/pypa/pipenv/issues/1013, but I am struggling to find the documentation.

**Comment by aleneum** [comment]
Hi @nicain,

> have you considered moving over to pipenv?

not yet but providing a Pipfile could be done if it eases the installation process.

> Optional dependencies are defined as in pypa/pipenv#1013

This just refers to flags of required packages but does not replace the project's own `extras_require` as far as I can tell.
For your personal project an entry like `transitions= { extras = ['diagrams'] }` in `[packages]` should to the trick.

To install optional dependencies for the project containing the `Pipfile` you have to do things like `pipenv install -e .[diagrams]` which just uses the `setup.py` (probably by calling `pip` with that option) to retrieve extra information.

I have not found another way to define optional dependencies in the `Pipfile` which can be used by pipenv directly. If you stumble upon such feature, let me know.

**Comment by tyarkoni** [comment]
Oh, hah, I didn't realize we already define a `'diagrams'` scheme in setup!

I don't know that moving to pipenv would buy us anything at this point. But we should perhaps update the installation section of the README to note that users who want to use the graphing tools should `pip install transitions[diagram]`.
