### ISSUE TITLE
Allow newer dill versions

### ISSUE THREAD

**Issue by dotlambda** [pytransitions/transitions#286]
19ec2ab introduced a constraint on the dill version.
Are the recursion errors still a problem? I do not see any when running the test suite with `dill==0.2.7.1`.

For cross-reference: NixOS/nixpkgs#34322

**Comment by aleneum** [comment]
Hello @dotlambda,

you are right. The workaround to cope with dill 2.7 and higher has been introduced in 0.6.0 according to the Changelog. The restriction is not required any longer. Python 3.3 had been problematic but should also work fine with dill 2.7.1 now. Will be removed shortly and thanks for the notice.
