### ISSUE TITLE
Use initial from embedded state machine on hierarchical state machines

### ISSUE THREAD

**Issue by mrjogo** [pytransitions/transitions#287]
Currently the `initial` keyword is needed even when the embedded state machine already defines it:

```python
# initial is set to '1'
counter = Machine(states=count_states, transitions=count_trans, initial='1')
# The 'counting' state's child state machine does not have '1' as the initial state
without_initial = ['waiting', 'collecting', {'name': 'counting', 'children': counter}]
# When it is explicitly set it behaves as expected
with_initial = ['waiting', 'collecting', {'name': 'counting', 'children': counter, 'initial': '1'}]
```

I'd propose using the child machine's initial setting unless overridden by a keyword setting in the child dictionary. This supports more separation of concerns, and is the expected behavior for me, at least.

**Comment by aleneum** [comment]
Hi @mrjogo,

sounds good to me. I assume your use case is more likely than halting in the 'meta' state of a passed HSM. Users who do not want to use the initial state of the passed HSM now have to explicitly mention that by passing `initial: False` now. Let's see if there is some feedback about this change before the next release.
