### ISSUE TITLE
Diagram features not supporting time-out extension

### ISSUE THREAD

**Issue by njbuch** [pytransitions/transitions#290]
Trying to document the state machine I am using, and having a problem with the timeout feature on the state.

Seems to be unsupported, or not working?

**Comment by aleneum** [comment]
Hello @njbuch, 

I am not aware of any issues related to the timeout feature. Could you please provide a) a minimal code example to show your problem and b) tell me which version of transitions you are using.

**Comment by njbuch** [comment]
Of course, I tried to minimize the example:
``from transitions import Machine
from transitions.extensions import GraphMachine
from transitions.extensions.states import add_state_features, Timeout

""" Use the decorator to add extensions """
@add_state_features(Timeout)
class CustomStateMachine(Machine):
    pass

class RPI_Controller(object):
    def __init__(self):
        self.entourage = 0
        self.received_data = 0

states = [{'name': 'sleep', 'timeout': 2, 'on_timeout': 'timeout2'},
          {'name': 'state4'}]

transitions = [['pin_high', 'sleep', 'state4'],
               ['timeout2', 'state4', 'sleep']]

controller = RPI_Controller()
machine = CustomStateMachine(model=controller, states=states, transitions=transitions, initial='sleep')


machine2 = GraphMachine(model=controller,
                       states=states,
                       transitions=transitions,
                       auto_transitions=False,
                       initial='sleep',
                       title="Mood Matrix",
                       show_conditions=True)

controller.get_graph().draw('my_state_diagram2.png', prog='dot')

**Comment by aleneum** [comment]
This code does not work. You define `CustomStateMachine` to be a subclass of `Machine` but later you initialise your machine with `machine2 = GraphMachine(model=controller, ...`.
`GraphMachine` uses `State` which does not know about the `timeout` feature.

First, you should make `CustomStateMachine` make a subclass of `GraphMachine` to inherit the diagram features and second you should also use this class for object initialisation. 
Additionally, using the same model (`controller`) for two state machines is not supported. 
The second machine will override the methods attached to the model by the first machine or raise an error if this method already exists. From the example code I cannot tell what the benefit of this approach may be but if there is a certain use case for this, I am all ears.

The working code looks like this:

```python
from transitions.extensions import GraphMachine
from transitions.extensions.states import add_state_features, Timeout


@add_state_features(Timeout)
class CustomStateMachine(GraphMachine):
    pass


class RPI_Controller(object):
    def __init__(self):
        self.entourage = 0
        self.received_data = 0


states = [{'name': 'sleep', 'timeout': 2, 'on_timeout': 'timeout2'},
          {'name': 'state4'}]

transitions = [['pin_high', 'sleep', 'state4'],
               ['timeout2', 'state4', 'sleep']]

controller = RPI_Controller()

machine = CustomStateMachine(model=controller,
                             states=states,
                             transitions=transitions,
                             auto_transitions=False,
                             initial='sleep',
                             title="Mood Matrix",
                             show_conditions=True)

controller.get_graph().draw('my_state_diagram2.png', prog='dot')
```

and produces this output

![my_state_diagram2](https://user-images.githubusercontent.com/205986/36588573-db4e70bc-1888-11e8-8310-4be72002f425.png)

which is what I would expect. Is there an issue I have overlooked?

**Comment by njbuch** [comment]
Thank you so much, I did not realize the inheritance hierarchy between the GraphMachine and Machine, which was the reason for two machines. The intention was to create a machine just for exporting the graph.

You have been really helpful, I appreciate it a lot. Will continue my state-machine adventure.

Thanks again :) 👍
