### ISSUE TITLE
Diagrams example in Readme typo?

### ISSUE THREAD

**Issue by Shaun-Griffith-Hive** [pytransitions/transitions#293]
In the readme, in the Diagrams section, `machine` is created, but never referenced. Should `m` be `machine`?

```
from transitions.extensions import GraphMachine as Machine
m = Model()
machine = Machine(model=m, ...)
# in cases where auto transitions should be visible
# Machine(model=m, show_auto_transitions=True, ...)

# draw the whole graph ...
m.get_graph().draw('my_state_diagram.png', prog='dot') # <== should this be machine.get_graph()?
```

**Comment by aleneum** [comment]
Hello @Shaun-Griffith-Hive,

the method `get_graph` is attached to the model by `Machine`. `get_machine` is a partial of `Machine._get_graph(model, ...)` with an already resolved `model` parameter. This way you can have multiple models and every model's `get_graph` will return the diagram and current state of the respective model. In other words, there is no need to reference the `Machine` instance directly.

**Comment by Shaun-Griffith-Hive** [comment]
Ah, thanks.
