### ISSUE TITLE
Fix PyPi description by publishing release 0.6.6

### ISSUE THREAD

**Issue by aleneum** [pytransitions/transitions#294]
The problem has been identified and solved. Just releasing a version because of this feels a bit too much though. If someone considers this a significant issue, please feel free to comment here.

**Comment by tedmiston** [comment]
I came here for this as well (and have seen / experienced similar issues on other projects with markdown on PyPI).  It looks like the 0.6.6 release fixes the issue.  Do you have an idea when it will be published?

**Comment by aleneum** [comment]
Hi @tedmiston,

I'd like to resolve #289 first. This should be done mid end next week.

**Comment by tedmiston** [comment]
Sounds great.  That looks like a cool feature.  Looking forward to it.

**Comment by aleneum** [comment]
Starting from [0.6.7](https://pypi.org/project/transitions/0.6.7/) this should be fixed on PyPI.
The process had been taken from [here](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi) and can be summarised as:

```bash
pyenv shell 3.6.4 
rm -r */dist
pip install -U setuptools twine wheel
python setup.py sdist bdist_wheel --universal
twine upload dist/*
```

I had to use Python 3 explicitly with `twine` since Python 2.7 did not work (as seen in 0.6.6).
