### ISSUE TITLE
Nested state example in readme.md gives error when graphing

### ISSUE THREAD

**Issue by Shaun-Griffith-Hive** [pytransitions/transitions#296]
When I converted the nested state example in readme.md to use graph (and skipping the issue with unicode), it complains:

```
/home/shaun/.virtualenvs/py36/lib/python3.6/site-packages/pygraphviz/agraph.py:1334: RuntimeWarning: Warning: C_2 -> C_anchor: tail is inside head cluster cluster_C

  warnings.warn(b"".join(errors).decode(self.encoding), RuntimeWarning)
```
(This is the latest pygraphviz from github,  36120f2.)

It does run, and gives an output. Is this expected given the example?

Code:
```
from transitions.extensions import HierarchicalGraphMachine as Machine
from transitions.extensions.nesting import NestedState
#NestedState.separator = '=>'
states = ['A', 'B',
  {'name': 'C', 'children':['1', '2',
    {'name': '3', 'children': ['a', 'b', 'c']}
  ]}
]

transitions = [
    ['reset', 'C', 'A'],
    ['reset', 'C_2', 'C']  # overwriting parent reset
]
```

![nesting_fsm](https://user-images.githubusercontent.com/29248651/38862382-aa08604e-422c-11e8-89e4-70d3f5875e11.png)

**Comment by aleneum** [comment]
Hi @Shaun-Griffith-Hive,

the graph looks correct despite the warning. The warning however is the result of an issue where arrow heads are not configured right when the source is a child of the destination. This should be fixed now.

**Comment by Shaun-Griffith-Hive** [comment]
Thanks. I've pulled down the latest master from github, no warnings.
