### ISSUE TITLE
Do conditions support config file?

### ISSUE THREAD

**Issue by WoWuQ** [pytransitions/transitions#304]
I want to read config file as transitions' conditions? what should i do？Create a dynamic function？ or other else？

thanks

**Comment by aleneum** [comment]
Hello @WoWuQ,

sorry for not answering you earlier. Have you tried asking this question on Stackoverflow? This sounds more like a question about how to use `transitions` rather than a bug report and/or feature request.

**Comment by aleneum** [comment]
I will close this issue for now since there has not been any feedback for 8 days. Feel free to comment on this issue if you have further feedback. I will reopen the issue if necessary.

**Comment by WoWuQ** [comment]
OK, I solve the problem , and  transitions can support the config file.
