### ISSUE TITLE
Timeouts not handled in the GraphMachine output

### ISSUE THREAD

**Issue by plaes** [pytransitions/transitions#305]
It seems that the timeout events are not rendered in the GraphMachine output.

**Comment by aleneum** [comment]
Hello @plaes,

apologies for not answering earlier. You are right, timeouts are not mentioned in graphs so far and I do agree that this should be mentioned somehow. Do you have a certain way in mind? I looked up some ways but maybe you know a standardised approach.

**Comment by plaes** [comment]
Unfortunately, neither do I. Maybe annotate like this: timeout(n, state) ?

**Comment by aleneum** [comment]
I guess it will be something along that line. Probably with a customisable string. Additionally, the time format needs to be adjustable or should adjust dynamically. Neither 'timeout(1200s)' nor 'timeout(0.02h)' is truly informative.
