### ISSUE TITLE
Next_state not Trigger trasition 

### ISSUE THREAD

**Issue by ncastrohub** [pytransitions/transitions#306]
When using add_ordered_transitions() method, with a model, states and transitios also with an after callback. 
I call model.next_state() and the transition is never triggered.

**Comment by aleneum** [comment]
Hello @ncastrohub, could you provide a minimal code example of the reported issue for me to reproduce it?

**Comment by aleneum** [comment]
Could you solve your issues @ncastrohub? I cannot investigate your reported problem without a lead. I can only investigate a reported bug, if the description and a code example allow me to reproduce it.
I close this issue for now. If your problem still exists, feel free to comment and I will open the issue again when it is confirmed that this is a bug.
