### ISSUE TITLE
Using StateMachine in ROS

### ISSUE THREAD

**Issue by ljaniec** [pytransitions/transitions#307]
I would like to use this library in one of my robotic systems. Example of how to use it in node-based approach would be really useful.

**Comment by paulbovbel** [comment]
I've used this library with ROS quite a bit. There's nothing special about how to use it with `rospy` in a 'node-based approach', just import it as you would any other python library, and go to town.

**Comment by aleneum** [comment]
Hi @ljaniec,

did you solve your issues? Unfortunately, I havent worked with ROS much and cannot be of assistance here.

**Comment by aleneum** [comment]
I will close this issue for now since there is no feature request or bug related to it. Feel free to comment and if necessary we will reopen the issue again.
