### ISSUE TITLE
Provide an option to disable internal logging

### ISSUE THREAD

**Issue by viper7882** [pytransitions/transitions#309]
My project contains logging information. When I enabled logging module together with pytransitions code, I found out that both logging actually appears together and I couldn't find any way to disable the logging in pytransitions. I'm wondering if you have a plan to provide an option not to enable logging by default? IMHO those who are interested to debug pytransitions codes shall turn on logging by passing in an debug option during machine construction. Turning on the logging in pytransitions codes by default causes annoyance to user like me, especially I can't turn it off.

**Comment by aleneum** [comment]
Hello @viper7882,

>  I couldn't find any way to disable the logging in pytransitions

the built-in logging module allows to disable logging -- or better set log levels -- for each module individually:

* [Python Logging - Disable logging from imported modules](https://stackoverflow.com/questions/35325042/python-logging-disable-logging-from-imported-modules)
* [How do I disable log messages from the Requests library?](https://stackoverflow.com/questions/11029717/how-do-i-disable-log-messages-from-the-requests-library)

```
import logging
logging.getLogger("transitions").setLevel(logging.WARNING)
```

As far as I know this is the recommended way to configure the logging behaviour of modules.

**Comment by aleneum** [comment]
I am closing this issue since there has been no feedback. If you think this problem is still valid feel free to comment. I will reopen the issue if necessary.
