### ISSUE TITLE
[Feature] [Request] Implement State History

### ISSUE THREAD

**Issue by doanguyen** [pytransitions/transitions#313]
As the title, it would be super helpful but I have not come up with a feasible idea yet, but people in event sourcing has done it before. Do you have time to implement or discuss it?

Btw, thanks a lot for a very good job!

**Comment by aleneum** [comment]
Hi @doanguyen,

what are you looking for? Just a list of state names? Since the stateful object with transitions is the *model* you can use the state property to track state changes:

```python
from transitions import Machine
import collections


# if you like your machine to act as a model, let Model inherit from Machine
class Model(object):

    def __init__(self, history_length):
        self.state_history = collections.deque(maxlen=history_length)

    @property
    def state(self):
        return self.state_history[-1]

    @state.setter
    def state(self, value):
        self.state_history.append(value)


model = Model(3)
machine = Machine(model, states=['A', 'B', 'C', 'D'], initial='A')
print(model.state)  # >>> A

model.to_B()
model.to_C()
model.to_A()
model.to_D()

print("->".join(model.state_history))  # >>> C->A->D
```

**Comment by doanguyen** [comment]
Hi,
I'm actually looking for a way of storing states and its transitions into database and re-initialize later.
After a while, I think storing events with triggered time could work as well.

**Comment by aleneum** [comment]
> I'm actually looking for a way of storing states and its transitions into database and re-initialize later

States are persistent objects maintained by a `Machine`. States can be pickled (serialized) and deserialized if necessary. However, the `State` objects themselves do not (or should not) contain actual state related properties. They are rather 'blueprints' to determine what should happen with a 'stateful' object which is a model.

You might want to have a look at [this issue](https://github.com/pytransitions/transitions/issues/146) or [this notebook](https://github.com/pytransitions/transitions/blob/master/examples/Frequently%20asked%20questions.ipynb) to get an idea how models and database table schemes can be connected.
This way you can save and load complete model/object states.

**Comment by doanguyen** [comment]
Thanks a bunch! I've got it.
