### ISSUE TITLE
State inheritance and incapsulating the logic in States

### ISSUE THREAD

**Issue by SuperChomsky** [pytransitions/transitions#319]
Hi, i am using Transitions for create my Finite State Machine. The problem is that i have got a big FSM with a lot of a state and a lot of instructions to do for each state. Is there a way to inheritance from State, create each State in a separate Class and incapsulate all the logic in these States? i Create a class wich inheritance from State, but the problem is that i could not write the callback like OnEnter() or OnExit() in this class because the model during runtime has not the reference

here is a simple example of what I would like to do

```
from transitions import Machine
from transitions import State

class MyFsm(object):    

   states=["A","C"]   

    transitions = [
        {'trigger': 'goInB','source':'A','dest':'B'},
        {'trigger': 'goInC','source':'B','dest':'A'}       
    ]    

    def __init__(self):      
       stateb = B()
       self.machine = Machine(model=self, states=self.states ,transitions=self.transitions, initial='A' )                    
       #HERE WHAT I WANT TO DO
       self.machine.add_state(stateb)      
    

    def goInB(self):
        print("trans goingB")
        
    def goInC(self):
        print("trans goingC")


#I WANT TO INCAPSULATE ALL THE LOGIC OF THE STATE: 'B', HERE. BUT THERE
#IS AN ERROR WITH THE CALLBACK, BECAUSE THE MODEL HAS NOT REFERENCE TO 'enterCallBack' & #'exitCallBack'
class B(State):    

    def __init__(self):      
        super().__init__(name='B',on_enter='enterCallBack',on_exit='exitCallBack')        
    
    def enterCallBack(self):
        print("entering state B")
        
    def exitCallBack(self):
        print("exiting state B")
        

myfsm = MyFsm()
myfsm.goInB()
```

Errore:
Traceback (most recent call last):
  File "C:\Users\...\core.py", line 1021, in resolve_callable
    func = getattr(event_data.model, func)
AttributeError: 'MyFsm' object has no attribute 'enterCallBack'

**Comment by potens1** [comment]
I don't know if it's the way to go, but, if you replace
```
super().__init__(name='B',on_enter='enterCallBack',on_exit='exitCallBack') 
```
with
```
super().__init__(name='B',on_enter=self.enterCallBack,on_exit=self.exitCallBack) 
```
It should work

**Comment by aleneum** [comment]
Hello @SuperChomsky,

this looks like a question about how to use transitions. Please refer to Stackoverflow for such matters.
Posting there has several advantages:

* Your question gains higher visibility since most developers look for help there
* The targeted community is larger; Some people will even help you to formulate a good question
* People get 'rewarded' with 'reputation' to help you. You also gain reputation in case this questions pops up more frequently. It's a win-win situation.

If your question results in feature request or a bug report, feel free to open a ticket.
