### ISSUE TITLE
Allow conditions to work with truthy and falsy values instead of just 'True' and 'False'

### ISSUE THREAD

**Issue by potens1** [pytransitions/transitions#326]
I don't know if this is something that is wanted, but it seems the `conditions` and `unless` are compared to the `True` or `False` value, not the boolean value of the expression, i.e:

```
from transitions import Machine

class TestMachine(Machine):
    def __init__(self):
        self.states = ["init", "ok", "nok"]
        self.transitions = [{
            "trigger": 'go',
            "source": 'init',
            "dest": "ok",
            "conditions": "is_ok"
        }, {
            "trigger": 'go',
            "source": 'init',
            "dest": "nok",
            "unless": "is_ok"
        }]
        machine = super().__init__(
            model=self,
            initial="init",
            transitions=self.transitions,
            states=self.states)

    def is_ok(self):
        return None


test = TestMachine()
test.go()
assert test.state == 'nok'

 >>> AssertionError: assert 'init' == 'nok'
```
Here, is_ok return None, so, it's boolean value is False, so, it should be the `unless` path that should be done but:
```
core.py                    256 DEBUG    Transition condition failed: is_ok() does not return True. Transition halted.
core.py                    246 DEBUG    Initiating transition from state init to state nok...
core.py                    256 DEBUG    Transition condition failed: is_ok() does not return False. Transition halted.
```
I know the doc talks about `True` and `False`, but, it sounds -at least to me- surprising.

Maybe do some add in doc to explain the comparison is _really_ done against True and False, not on the boolean value of the expression.

**Comment by aleneum** [comment]
Hi @potens1,

sorry for the long wait. It  has been a deliberately decision to only accept `True` and `False` instead of 'truthy' and 'falsy' values such as (non)empty strings, lists and so on for the sake of comprehensibility of condition checks.
Thats why the documentation always states `True` and `False` instead of `true` and `false`.
However, if community feedback favours changing conditions to also work with 'falsy' and 'truthy' values it can be done. I will leave the ticket open with a request for feedback.

**Comment by aleneum** [comment]
Condition changes to:

```python
# Condition.check(self, event_data) 
if event_data.machine.send_event:
    res = predicate(event_data)
else:
    res = predicate(*event_data.args, **event_data.kwargs)
return res if self.target else not res
```

**Comment by potens1** [comment]
Sorry, I did not understood you where expecting an answer from my side (was thinking your last message was to signify that this change was acted)
My point of view is this is strange the current implementation can lead to cases where you have conditions and unless (for two transitions), with the same "condition" statement, to no transition at all.
The thing is I don't see correct way (meaning logical and without magic or surprise) to do it without doing what you wrote in your comment.
The other way could be to say that "unless" is equal to "not conditions", but this way, conditions are evaluated against True or False, and unless is "`is not True`" (and that's different from "`is False`")
So, if you choose to keep it the way it is, I'm fine with that, the think is to know this situation can happend (my_condition is not True and my_condition is not False -> no transition)

**Comment by aleneum** [comment]
Hi @potens1:

> Sorry, I did not understood you where expecting an answer from my side (was thinking your last message was to signify that this change was acted)

No action from you required. You made your point clear. I was hoping for someone from the user base to (dis-)agree with you as written in:

> 'However, if community feedback favours changing conditions to also work with 'falsy' and 'truthy' values it can be done.'

I now see how this can be misinterpreted, sorry. I don't have a strong opinion about that and I think you presented your arguments well. To evaluate whether this would be a desired change, more feedback is required. I reopen the issue again for visibility.

**Comment by InbarRose** [comment]
If your "unless" check is  "not condition" then that should be your check, and that will return False if condition is not True. But otherwise "unless" could be something else entirely.

I think requiring "True" and "False" is a good idea.

I originally came here thinking that I might agree with truthy and falsey, but after seeing the conversation, I have to say that I prefer it being stricter.

**Comment by aleneum** [comment]
I will close this issue for now since it went stale. Feel free to comment if you still think `transitions` would notably benefit from the proposed feature. I will reopen the issue if required. Thank you for making `transitions` better by sharing your insights @potens1 and @InbarRose!
