### ISSUE TITLE
Same code with Different result by different installment!!

### ISSUE THREAD

**Issue by liuzongquan** [pytransitions/transitions#327]
hi all,
   the following code execute on different envs with different results, that's so Weird！
sample code:

```
#!/usr/bin/env/python
#-*- coding: utf-8 -*-
from transitions import Machine
import sys 
import logging
logging.basicConfig(level=logging.DEBUG)
#Set transitions' log level to INFO; DEBUG messages will be omitted
logging.getLogger('transitions').setLevel(logging.DEBUG)

class DST(object):

    def __init__(self):
        
        self.states = ['A', 'B', 'C']
        self.initial_state = 'A'

        self.machine = Machine(model=self, states=self.states, initial=self.initial_state)
        self.machine.add_transition(source='A', dest='B', trigger='go', conditions='check_cond')
        self.machine.add_transition(source='A', dest='C', trigger='go', conditions='check_cond')

        
    def go(self):
        pass
    
    def check_cond(self):
        return True
    



if __name__ == '__main__':
    test_case = DST()
    print (test_case.state)
    test_case.go()
    print (test_case.state)
```
Envs-1: pip install transitions
the result is expected:

> A
DEBUG:transitions.core:Initiating transition from state A to state B...
DEBUG:transitions.core:Exiting state A. Processing callbacks...
INFO:transitions.core:Exited state A
DEBUG:transitions.core:Entering state B. Processing callbacks...
INFO:transitions.core:Entered state B
B

Envs-2: git clone https://github.com/pytransitions/transitions.git and then python setup.py install
the result is Wrong!

> WARNING:transitions.core:Model already contains an attribute 'go'. Skip binding.
A
A

Any body encounters the same problem?

**Comment by liuzongquan** [comment]
@aleneum

**Comment by aleneum** [comment]
The question arises 'how do I call the trigger then?'. Currently this is rather complicated. I have refactored the convenience model method 'Model.trigger' to work independently of the binding status of Events. In case your `DST.go` needs to stay you can still call the event `go` the following way:

```
if __name__ == '__main__':
    test_case = DST()
    print(test_case.state)  # >>> A
    test_case.go()
    print(test_case.state)  # >>> A
    test_case.trigger('go') # <<< call trigger with trigger name.
    print(test_case.state)  # >>> B
```
