### ISSUE TITLE
Hierarchical logic problem

### ISSUE THREAD

**Issue by kentoshima** [pytransitions/transitions#329]
like the sample in Hierarchical State Machine
if machine is in "caffeinated_walking" or "caffeinated_dithering" state , the value of machine.caffeinated should be True.  but i got a False

**Comment by aleneum** [comment]
Hi @kentoshima,

the documentation right above [here](https://github.com/pytransitions/transitions#reuse-of-previously-created-hsms) mentions the following:

> To check whether the current state is a substate of a specific state is_state supports the keyword allow_substates:

```
machine.state
>>> 'C.2.a'
machine.is_C() # checks for specific states
>>> False
machine.is_C(allow_substates=True)
>>> True
```

So this should work:

```
from transitions.extensions import HierarchicalMachine as Machine

states = ['standing', 'walking', {'name': 'caffeinated', 'children':['dithering', 'running']}]
transitions = [
  ['walk', 'standing', 'walking'],
  ['stop', 'walking', 'standing'],
  ['drink', '*', 'caffeinated'],
  ['walk', ['caffeinated', 'caffeinated_dithering'], 'caffeinated_running'],
  ['relax', 'caffeinated', 'standing']
]

machine = Machine(states=states, transitions=transitions, initial='standing')
machine.drink() # coffee time
machine.walk()
print(machine.state)  # caffeinated_running
print(machine.is_caffeinated())  # >>> False
print(machine.is_caffeinated(allow_substates=True))  # >>> True
```

**Comment by kentoshima** [comment]
> Hi @kentoshima,
> 
> the documentation right above [here](https://github.com/pytransitions/transitions#reuse-of-previously-created-hsms) mentions the following:
> 
> > To check whether the current state is a substate of a specific state is_state supports the keyword allow_substates:
> 
> ```python
> machine.state
> >>> 'C.2.a'
> machine.is_C() # checks for specific states
> >>> False
> machine.is_C(allow_substates=True)
> >>> True
> ```
> 
> So this should work:
> 
> ```python
> from transitions.extensions import HierarchicalMachine as Machine
> 
> states = ['standing', 'walking', {'name': 'caffeinated', 'children':['dithering', 'running']}]
> transitions = [
>   ['walk', 'standing', 'walking'],
>   ['stop', 'walking', 'standing'],
>   ['drink', '*', 'caffeinated'],
>   ['walk', ['caffeinated', 'caffeinated_dithering'], 'caffeinated_running'],
>   ['relax', 'caffeinated', 'standing']
> ]
> 
> machine = Machine(states=states, transitions=transitions, initial='standing')
> machine.drink() # coffee time
> machine.walk()
> print(machine.state)  # >>> caffeinated_running
> print(machine.is_caffeinated())  # >>> False
> print(machine.is_caffeinated(allow_substates=True))  # >>> True
> ```

thank you!
i should read the doc carefully next time
