### ISSUE TITLE
Feature Request: Display accepted states in GraphMachine diagrams

### ISSUE THREAD

**Issue by peey** [pytransitions/transitions#330]
Using the `Error` feature, I can specify which states are "accepted"

It would be great if we distinguish between the accepted states and unaccepted states in the diagram when using this feature.

**Comment by aleneum** [comment]
Hi @peey,

starting with `0.7.0` transition will support tags in diagrams. Have a look at the [diagram](https://github.com/pytransitions/transitions/tree/next-release#-diagrams) section in the `next-release` branch. States tagged with accepted should be fairly easy to distinguish.

**Comment by peey** [comment]
Oh, this is wonderful! From what I understand, accepted will be listed as a tag, correct?

I think that should be good enough. One possible enhancement could be to give special notation to accept states. e.g. this ([source](https://commons.wikimedia.org/wiki/File:CPT-FSM-abcd.svg)):

![](https://upload.wikimedia.org/wikipedia/commons/2/2a/CPT-FSM-abcd.svg)

Here, S4 is a final state. This double circle is one notation I've seen commonly in books for automata.

**Comment by aleneum** [comment]
yeah, this functionality could be extended by updating the node's attributes based on the state's tags. When using `pygraphviz`, the node can be accessed and updated like this already:
```python
from transitions.extensions.diagrams import GraphMachine

m = GraphMachine(states=['S1', 'S2', 'S3', 'S4'], auto_transitions=False, ordered_transitions=True, initial='S1')
m.next_state()  # go to S2
m.get_graph().get_node('S4').attr.update(peripheries=2)  # edit style of S4 
m.get_graph().draw('diagram.png', prog='dot')  # save diagram
```

![diagram](https://user-images.githubusercontent.com/205986/50147169-c0e3c700-02b5-11e9-802b-eb73ae6e0828.png)

**Comment by peey** [comment]
Oh. Thanks for telling me about this. I'll use this to customize the graph to look like how I want it. 

You can choose to keep this issue open if you want to invite further discussion on this / incorporate it into the lib or close if you think it's too niche.

**Comment by aleneum** [comment]
I will close this issue for now. Having custom styles based on tags sounds like a neat idea but does require some changes. Should this feature request resurface we can consider if its worth the effort.
