### ISSUE TITLE
Multiple models in a single machine, each having different states and triggers and callback methods

### ISSUE THREAD

**Issue by amitabhn** [pytransitions/transitions#331]
Is it possible to create a single machine containing multiple models, where each model has its own states, triggers and callback methods. In other words, each model actually implements a completely different state machines that is independent of the other models (except for a few triggers that need to be sent to all models), yet all of them are part of the same machine.

**Comment by aleneum** [comment]
Hello @amitabhn,

as mentioned in the [Readme](https://github.com/pytransitions/transitions#alternative-initialization-patterns):

> A machine can handle multiple models which can be passed as a list like Machine(model=[model1, model2, ...]) [...] You can also create a standalone machine, and register models dynamically via machine.add_model

The `Machine` instance acts as a 'rulebook' in that case. The models however are isolated, can implement their own state- or transition-related behaviour. However, all models will be decorated with all available triggers. This shouldn't be a problem as invalid triggers will raise a `MachineError`.
Issues may occur when wildcards '*' are used for defining transitions as the resulting transitions might be valid on all models and will therefore change the state of all models to the same.
It is recommended to not use wildcards in this case.

```python
from transitions import Machine

transitions = [dict(trigger='advance', source='A1', dest='B1', conditions='check'),
               dict(trigger='progress', source='A2', dest='B2', conditions='check'),
               dict(trigger='go', source='B1', dest='C1'),
               dict(trigger='go', source='B2', dest='C2')]


class Model1:

    def check(self):
        print("Everything good!")
        return True

    def on_enter_B1(self):
        print("Entered first state")


class Model2:

    def check(self):
        print("Everything better than good!")
        return True

    def on_enter_B2(self):
        print("Entered second state.")


model1 = Model1()
model2 = Model2()

machine = Machine(model=None, states=['A1', 'A2', 'B1', 'B2', 'C1', 'C2'], transitions=transitions)
machine.add_model(model1, initial='A1')
machine.add_model(model2, initial='A2')

# triggers can be called for models individually
model1.advance()  # >>> Everything good!\n Entered first state.
model2.progress()  # >>> Everything better than good!\n Entered second state.

# Dispatch will call a trigger on all models
machine.dispatch('go')  # >>> equivalent to model1.go(); model2.go();
print(model1.state, model2.state)  # C1 C2
```

**Comment by amitabhn** [comment]
Hi @aleneum, thanks for your reply.

I understood what you're saying. I can think of creating the Models separately with their own lists of States and Transitions, and then while creating the Machine, pass both Models and the concatenation of their States and Transitions.

In a further extension to my question, I also need to _exchange_ triggers between the two models (triggers generated by one and consumed by the other).
Is there any mechanism to do so? 
Or maybe a mechanism to _dispatch_ a trigger to the machine _from within the model_?



> Issues may occur when wildcards '*' are used for defining transitions as the resulting transitions might be valid on all models and will therefore change the state of all models to the same.
> It is recommended to not use wildcards in this case.

As for the wildcard issue, I am only using wildcards to register events that may arrive in any state, but are only required in a specific state.

```
transitions = [
	{
	    'trigger': 'trig_x',             # takes precedence
	    'source' : 'wait_for_x',
	    'dest'   : 'next_state',
	},
	{
	    'trigger': 'trig_x',
	    'source' : '*',
	    'dest'   : None,
	    'prepare': 'prepare_trig_x'
	}
]

class Model1:

	def prepare_trig_x():
		self.flag_x = True

	on_enter_wait_for_x():
		if self.flag_x is True:
			self.flag_x = False
			self.trig_x()
```

This is basically the functionality of a _deferred event_, which I believe is not supported by pytransitions.
Any ideas about a better way to achieve this?

**Comment by aleneum** [comment]
> In a further extension to my question, I also need to exchange triggers between the two models (triggers generated by one and consumed by the other).

Easiest solution would be simple membership, wouldn't it?

```python
class Model:
     # ...
    def trigger_x(self):
        self.target_model.trigger_x() 
```

>  Or maybe a mechanism to dispatch a trigger to the machine from within the model?

You can set `send_event=True` in `Machine`. This results in every callback having access to the triggering event which contains the targeted model as well as the machine instance. See the README for more details.

> This is basically the functionality of a deferred event. which I believe is not supported by pytransitions.

Explicitly? No. But it can be modeled without much effort though:

```python
transitions = [
    {'trigger': 'trigger_x', 'source': 'X', 'dest': None, 'after': 'process_event'},
    {'trigger': 'trigger_x', 'source': '*', 'dest': None, ('conditions': 'is_deferable'), 'after': 'defer'}, 
... ]

class Model:
    ...
    def on_enter_X(self):
        for event in self.deferred:
            self.process_event(event)
```

Validity of transitions for each event will be evaluated in the order they were added. This means for state `X` the second transition is never evaluated unless there is an additional condition that fails.

**Comment by aleneum** [comment]
Since there has been no follow up I will close the issue for now. If you consider this issue not resolved, please comment and I will reopen the issue if necessary.
