### ISSUE TITLE
Nested machine not working as expected

### ISSUE THREAD

**Issue by keivanzavari** [pytransitions/transitions#332]
Hi 
I have been looking at closed issues, SO, and googling to solve this issue. But I haven't been able to solve my problem and this seems to be the only way to describe it and hope to get an answer.
I am making a state machine which can include several substates which are also all state machines. So this basically boils down to reusing HSM according to readme.

my highest level SM looks like this:
```python
from transitions.extensions import LockedHierarchicalMachine as Machine
from coordination.running import RunningStateMachine

logging.basicConfig(level=logging.ERROR)
logging.getLogger("transitions").setLevel(logging.INFO)

class RPPStateMachine(Machine):
    def __init__(self, name):
        self._running = RunningStateMachine()
        self.name = name
        states = [
            "init",
            {"name": "running", "children": self._running},
            "stop",
        ]

        Machine.__init__(self, states=states, initial="init")

        self.add_transition("e_run", "init", "run", after=self.run_machine)
        self.add_transition("e_stop", "*", "stop")

    def run_machine(self):
        self._running.initialize()
```
As you see a state machine with three states `init`, `running` and `stop`. Once the event `e_run()` is sent via something like
```python
machine = RPPStateMachine("my_machine")
machine.e_run()
```
machine transitions to `running` state. 
_I do it in an indirect way because I wanted things to happen automatically. `e_run()` transitions to `running` and after `run_machine` calls `initialize` method of running class which fires an event to start up the chain of events. Below I show `running` and that clears thing up._

So the running state is defined as

```python
from transitions.extensions import LockedHierarchicalMachine as Machine
from coordination.test_mode import TestingStateMachine
from coordination.release_mode import ReleaseStateMachine

class RunningStateMachine(Machine):
    def __init__(self):
        self._test_mode = TestingStateMachine()
        self._release_demo = ReleaseStateMachine()
        states = [
            "init",
            "configuration",
            "idle",
            {"name": "test_mode", "children": self._test_mode},
            {"name": "release_mode", "children": self._release_mode},
        ]

        Machine.__init__(self, states=states, initial="init")
        self.add_transition("e_start_running", "init", "configuration", after=self.configuration)
        self.add_transition("e_success_config", "configuration", "idle")
        self.add_transition("e_test_mode", "idle", "test_mode")
        self.add_transition("e_release_mode", "idle", "release_mode")
        self.add_transition("e_start_running", "idle", "init")

    def initialize(self):
        print("Initialization step for running, emitting e_start.")
        self.e_start_running()

    def configuration(self):
        print("Configuring...")
        print( "Current state: " + self.state)

        self.e_success_config()
```

which similar to its parent, is composed of a few states and a few substates.
I have also enabled logging to see which states I enter and exit. To my experience, nesting state machines is very useful as you can reuse the states you have written before. Besides as your state machine grows, it helps to keep things more modular. So no state becomes huge and difficult to read/understand.

So the unusual behavior is that when `e_run()` is called I get prints of
```python
INFO:transitions.core:Entered state running
INFO:transitions.core:Entered state running_init
Initialization step for running, emitting e_start.
INFO:transitions.core:Exited state init
INFO:transitions.core:Entered state configuration
Configuring...
current state: configuration
INFO:transitions.core:Exited state configuration
INFO:transitions.core:Entered state idle
```

As you see 
```python
machine.state
>>> 'running_init'
```
while
```python
machine._running.state
>>> 'idle'
```

I can of course move the transition definitions to the parent state, but that's unhandy. I cannot do that for all sub-states. Obviously, I want each substate to be responsible for it's own behavior. What is the common practice? Is this a bug or intended behavior?

**Comment by keivanzavari** [comment]
I think I have figured out what the problem is (correct me if I am wrong please). Once you create a state with children (sub-state) as
```python
self._running = RunningStateMachine()
{"name": "running", "children": self._running},
```
a copy of the sub-state is created. That's why `machine._running` and `machine` are in different states. Copying is fine by me, but the drawback is the following:

## drawback
If there are callbacks inside the sub-state who are supposed to do stuff and then trigger events, they cannot do their job anymore.
I can create a transition in the parent state as
```python
self.add_transition("e_start_chain", "running_init", "running_configuration")
```
and trigger this event immediately after the call of `e_run()`. So I would do
```python
machine.e_run() # machine state = running_init
machine.e_start_chain() # machine state = running_configuration
```
However, since configuration method in `RunningStateMachine` class has `self.e_success_config()`, triggering this event raises an error because the sub-state defined by `machine._running` is obviously in `init` state and I get the error of `Can't trigger event e_success_config from state init!`. But triggering `machine.e_success_config()` does the job.

## still vague
So what is the right way to be able to fully reuse a machine as a sub-state of another?
Does my parent machine need to inherit from the sub-state?

**P.S.** If the sub-state is copied, how deep does this copy go? Until it reaches the leaves? Or does it stop somewhere?

**Comment by aleneum** [comment]
Hello @keivanzavari,

> To my experience, nesting state machines is very useful as you can reuse the states you have written before. Besides as your state machine grows, it helps to keep things more modular. So no state becomes huge and difficult to read/understand.

totally agree

> I think I have figured out what the problem is (correct me if I am wrong please). Once you create a state with children (sub-state)  [...]  a copy of the sub-state is created.

yes, that's mentioned in the last paragraph of the reuse [section](https://github.com/pytransitions/transitions#reuse-of-previously-created-hsms):

> Note that the HierarchicalMachine will not integrate the machine instance itself but the states and transitions by creating copies of them. This way you are able to continue using your previously created instance without interfering with the embedded version.

> If the sub-state is copied, how deep does this copy go?

All states and substates will be integrated into the new `Machine`

> So what is the right way to be able to fully reuse a machine as a sub-state of another?

I cannot claim this is the 'right' way because using machines *in* machines is a common practice for realizing HSMs afaik. So your initial thoughts are pretty much in line with how some state machine frameworks work. However, `transitions`' philosophy differs a bit here: we'd like to consider `Machine` instances to be the 'rulebooks' which defines transitions and configurations whereas the actual state-dependent behavior is part of the model.

---
I am working on an example to illustrate how that could look like and will update that answer when I am done

---

**Comment by keivanzavari** [comment]
Thanks for the answer, much appreciated. 
In the meantime, I changed the implementation to just one machine that has all the states. So in the example above `RunningStateMachine` is incorporated into the parent state machine.
If my state machine grows, I'll have to find ways to fix this. I have previously used rFSM and made quite complicated state machines. There it's very easy to load another state machine without having to know what's inside of it [like here](https://github.com/kmarkus/rFSM/blob/master/doc/rFSM-manual.md#how-to-compose-state-machines).

So I would very much like to use some smaller states as a sort of plug and play modules and do not have to tweak with them. If I understand you correctly, I'll have to load each state as a separate model, right?
So for my example above it would be separate `add_model` calls. What if one state machine needs to use another?

**Comment by aleneum** [comment]
> There it's very easy to load another state machine without having to know what's inside of it [...]
So I would very much like to use some smaller states as a sort of plug and play modules and do not have to tweak with them.

I see the appeal of that. I'd assume it can be done with `transitions` as well. Since callbacks can also be function/method references instead of strings. The degree of isolation depends on how the module is defined:

```python
class BehaviorA:
    def __init__(self):
        states = [{'name': 'A', 'on_enter': self.do_something}, ...]
        transitions = [{'trigger':'foo', ..., 'prepare': self.prepare,
                        'conditions': 'model_callback'}, ...]
        # initialized machine without model
        self.machine = Machine(model=None, states=states,
                               transitions=transitions, initial=...)
```

However, it might not be as convenient as it should be. Feel free to give feedback about your experience and how to improve the handling of nested states.

>  If I understand you correctly, I'll have to load each state as a separate model, right?

The states and transitions are defined for the machine. However, the model is the actual 'stateful' object and contains the state- and transition-related callbacks.
I'd suggest to isolate context-specific behaviour into a machine-model unit.

**Comment by aleneum** [comment]
I created a feature draft based on this discussion and will close this issue for now.  Thank you for your feedback! If you have a good test case for convenient nesting (with possible corner cases), feel free to post it here or in the issue mentioned above.
