### ISSUE TITLE
Flexible state type

### ISSUE THREAD

**Issue by justinttl** [pytransitions/transitions#334]
**Problem**
Currently, it is impossible to define states for a machine as an iterable collection of objects (Enums).
 
![image](https://user-images.githubusercontent.com/9387665/52018141-6f834600-24b7-11e9-99cd-babfd3b2b821.png)

Considering that it is now possible to set callbacks directly with reference to the Callable (#82 #83), this seems like another step to remove more loose string based referencing. More type hint + intellisense \m/

![image](https://user-images.githubusercontent.com/9387665/52016856-a8b9b700-24b3-11e9-9e60-9a223d23a60a.png)

If you attempt to feed in a list of Enum objects...
![image](https://user-images.githubusercontent.com/9387665/52017875-aa38ae80-24b6-11e9-8b09-e5e1ff759ea8.png)

**Feature Request**
It would be nice if passing states as Enums or any generic iterable is natively supported.

**Comment by aleneum** [comment]
Hi @JustinTTL,

interesting idea. Currently, I am working with string constants but enums sound also reasonable.
Let's see what others might have to add to this.

**Comment by JustinTTL** [comment]
Sounds good! Would love to hear other user's thought on this. 

I personally like hard typing everything instead of loose references. Having intellisense + mypy type checks whenever possible really helps with faster development

**Comment by artofhuman** [comment]
+1 for this feature

**Comment by paulbovbel** [comment]
+1 for native enum handling, I currently end up with boilerplate such as:

```
machine = Machine(
    states=list(States.__members__.keys()))

machine.add(States.INITIAL.name, States.NEXT.name, 'trigger)
...
```

**Comment by artofhuman** [comment]
I have a custom state machine for this workaround

``` python
from enum import EnumMeta
from collections.abc import Iterable

from transitions import Machine, State


class EnumState(State):
    def __init__(self, value, *args, **kwargs):
        self.name = value.name.lower()
        self.value = value
        super().__init__(self.name, *args, **kwargs)

    def __eq__(self, other):
        return isinstance(other, EnumState) and self.value == other.value


class EnumStateMachine(Machine):
    def set_state(self, state, model=None):
        if isinstance(state, str):
            state = self.get_state(state).value
        model.state = state

    def get_state(self, state):
        if isinstance(state, str):
            return super().get_state(state)
        else:
            return super().get_state(state.name.lower())

    def is_state(self, state, model):
        return model.state == self.get_state(state).value

    def add_transition(self, trigger, source, dest, *args, **kwargs):
        if isinstance(source, Iterable):
            source = [EnumState(state) for state in source]
        else:
            source = EnumState(source)

        dest = EnumState(dest)

        super().add_transition(trigger, source, dest, *args, **kwargs)


def init_state_machine(instance, states: EnumMeta, **kwargs) -> EnumStateMachine:
    instance.machine = EnumStateMachine(
        model=instance,
        states=[EnumState(state) for state in states],
        initial=EnumState(states(instance.state)),
        auto_transitions=False,
        **kwargs
    )

    return instance.machine

```

**Comment by aleneum** [comment]
Starting with 6181bebd6374fdd55b4a35bab3c747a2dd1dc38e, enumerations are now supported. Enums cannot be nested in `HierarchicalStateMachine` right now though as they do not contain hierarchical information (`Machine.get_state` does not know where to find them). Enum support will be part of the `0.7.1` release. But before `0.7.1` is released I'd like to wait a bit if someone encounters bugs or shortcomings. 

Thanks to @artofhuman for the PR #357, @justinttl for the feature suggestion and @paulbovbel for your feedback. I will close this issue for now. If you find bugs, please create new issues.

**Comment by artofhuman** [comment]
Awesome 👍

**Comment by justinttl** [comment]
🍾
