### ISSUE TITLE
Set state doesn't trigger on_enter

### ISSUE THREAD

**Issue by mumrau** [pytransitions/transitions#338]
Hello,

I have a machine which gets its initial state dinamycally assigned, and I can't get the `on_enter` of my desired initial state to run.
I know that the `on_enter` is not triggered on the initial state, taht's why I am using a dummy state and then calling `set_state(my_dynamic_state)`. Nonetheless, this event doesn't trigger the desired `on_enter` method.
It doesn't look coherent with the table describing the callbacks order in the documentation that's why I'm quite surprised, there might be a bug given the expected behavior.

Thank you in advance, the library is quite awesome anyway !!
EDIT: my workaround is the following:
```python
on_enter = getattr(model, "to_" + entry.phase)
    on_enter()
```
But it isn't really elegant to be honest.

**Comment by aleneum** [comment]
Hello @mumrau,

`Machine.set_state` circumvents callbacks and sets a state directly. I'd suggest an using [auto transitions](https://github.com/pytransitions/transitions#automatic-transitions-for-all-states) (`model.to_<state_name>`) from your initial state to trigger the described order of callbacks.

**Comment by mumrau** [comment]
Yes that is what I'm doing @aleneum, the snippet upwards does exactly that but I find it really inelegant to be honest...

The API really lacks a mechanism (that might be just that) to obfuscate this behavior like:
```
go_to_state('my-state')
```
You need to not start just by `to_` of course to avoid collisions, but I believe this is a point that seems quite logical to plenty other people: having the possibility to move to a state by its name more "dynamically" by simply using strings.

**Comment by aleneum** [comment]
I see.

Have a look at `NestedMachine` and `NestedMachine.to_state` in particular. `NestedMachine.add_model` assigns a `to` function to a model which probably does what you need:

```python
from transitions.extensions.nesting import HierarchicalMachine as Machine


class Model:

    def on_enter_A(self):
        print("Entered A!")

model = Model()
m = Machine(model, states=['A'])

assert model.state == 'initial'
model.to('A')  # >>> Entered A!
assert model.state == 'A'
```

**Comment by mumrau** [comment]
Mhh that's interesting, thanks !
Anyway, I'd rather stick with my "hack" using introspection for now, I'd rather not get into HierarchicalMachines, I need it to stay dead simple for my use case.

Could the implementation of a more abstract `go_to(phase)` make it upstream someday or is there a design decision against it? 
This can be discussed in another issue tho :)

**Comment by aleneum** [comment]
> Could the implementation of a more abstract go_to(phase) make it upstream someday 

It depends. It hasn't been requested so far and we'd encourage to rather work with events.
There is no easy way to distinguish between auto transitions and manually added transitions.
An integrated `Machine.to_state` would either more or less do what you are currently doing or create events on the fly like the workaround in `HierarchicalMachine`.
If you need `Machine` to support it, you can just add the functionality yourself in a `CustomMachine` to limit the overhead:

```python
from transitions import Machine
from transitions.core import Event, EventData


class Model():
    pass


class CustomMachine(Machine):

    def to_state(self, model, state_name, *args, **kwargs):
        event = EventData(self.get_state(model.state), Event('to', self), self,
                          model, args=args, kwargs=kwargs)
        self._create_transition(model.state, state_name).execute(event)


model = Model()
machine = CustomMachine(model, states=['A','B'], initial='A')
machine.to_state(model, 'B')
```

Alternatively, you could create transitions/events since transitions already supports calling events by their name:

```python
from transitions import Machine


class Model:
    pass


states = ['A', 'B']
# creates a transition named 'state' from each state  ('*') to state 'state'
transitions = [[state, '*', state] for state in states]  

model = Model()
machine = Machine(model, states=['A', 'B'], transitions=transitions, initial='A')
model.trigger('B')
assert model.state == 'B'
```

**Comment by mumrau** [comment]
Thank you for your impressive and complete feedback! 
I'd settle for the CustomMachine implementation, I thought about it too but time was of the essence so I rushed with the introspection.
