### ISSUE TITLE
get_models feature request

### ISSUE THREAD

**Issue by dprouse** [pytransitions/transitions#339]
It would be cool if a list of models could be retrieved that have been added using add_model(). What wold be cooler is if the get_model function took a state argument and returned all models in that state.

**Comment by aleneum** [comment]
Hello @dprouse,

> a list of models could be retrieved that have been added using add_model().

`Machine.models` which a list of all currently associated models

> What wold be cooler is if the get_model function took a state argument and returned all models in that state.

This can be done with a simple list comprehension such as `[model for model in machine.models if model.state == 'state']`.

See this example:
```python
from transitions import Machine


class Model():

    def __init__(self, name):
        self.name = name


model1 = Model('model1')
model2 = Model('model2')
model3 = Model('model3')
model4 = Model('model4')

m = Machine(model1, states=['A', 'B', 'C'], transitions=[['go', 'A', 'B'], ['go', 'B', 'C']], initial='A')
m.add_model(model2)
m.add_model(model3)
m.add_model(model4)

model1.go()  # state = B
model1.go()  # state = C
model2.go()  # state = B

stateA = [model.name for model in m.models if model.state == 'A']
stateB = [model.name for model in m.models if model.is_B()]  # using convenience functions

print(stateA)  # ['model3', 'model4']
print(stateB)  # ['model2']
```

In my opinion this is already pretty straight forward and comprehensible.
