### ISSUE TITLE
Async support lacks support for State.enter/exit and cannot handle synchronized conditions

### ISSUE THREAD

**Issue by aleneum** [pytransitions/transitions#341]
Currently, not every callback in `dev-async` is handled correctly. Found by @ablakey in #259.

**Comment by aleneum** [comment]
@ablakey: I refactored core and async to work with `Machine.callbacks` which removes some now unnecessary overrides. I also check in `AsyncCondition` whether the predicate is a coroutine or not.
The previously failing tests seem to work now. Let me know if that also fixes the issues you have encountered.

**Comment by ablakey** [comment]
Yup everything's working on my end.  Thanks for the really quick response!

**Comment by aleneum** [comment]
Awesome. Thank you for your investigation. I will close this issue for now. Feel free to comment if similar issues arise. I will reopen the issue if necessary.
