### ISSUE TITLE
Proposal for "during" action in addition to "entry" and "exit".

### ISSUE THREAD

**Issue by slovak194** [pytransitions/transitions#342]
Hi!

I like "transitions", but I also had a nice experience working with another FSM framework (another language) and what is really missing for me in "transitions" is a "during" action callback.

**during Actions:**
During actions are executed when a state is active, an event occurs, and no valid transition to another state is available.

I see that there is a possibility to emulate this with inner transitions with "prepare" callback, but it is not exactly the same.
Is it desired to extend functionality of "transitions" with such semantic?

BR,
Alex

**Comment by aleneum** [comment]
Hello @slovak194,

sorry for the late answer. Currently, there is no plan to add a `during` callback to `transition`. However, depending on the community feedback this might change in the future. 

> I see that there is a possibility to emulate this with inner transitions with "prepare" callback, but it is not exactly the same.

`State` can be extended to deal with a new callback quite easily. Configuring `Event` is a bit more tricky. Making your custom `DuringMachine` using `DuringState` and `DuringEvent` can also be done quite easily:

```python
from transitions.core import Machine, State, Event, EventData, listify


class DuringState(State):

    dynamic_methods = State.dynamic_methods + ['on_during']
    
    def __init__(self, *args, **kwargs):
        during = kwargs.pop('during', [])
        self.on_during = listify(during)
        super(DuringState, self).__init__(*args, **kwargs)

    def during(self, event_data):
        for handle in self.on_during:
            event_data.machine.callback(handle, event_data)


class DuringEvent(Event):

    def _trigger(self, model, *args, **kwargs):
        res = super(DuringEvent, self)._trigger(model, *args, **kwargs)
        if not res:
            state = self.machine.get_state(model.state)
            event_data = EventData(state, self, self.machine, model, args=args, kwargs=kwargs)
            event_data.result = res
            state.during(event_data)
        return res


class DuringMachine(Machine):

    state_cls = DuringState
    event_cls = DuringEvent


class Model:

    def on_during_A(self):
        print("Dynamically assigned callback")

    def another_callback(self):
        print("Explicitly assigned callback")


model = Model()
machine = DuringMachine(model=model, states=[{'name': 'A', 'during': 'another_callback'}, 'B'],
                        transitions=[['go', 'B', 'A']], initial='A', ignore_invalid_triggers=True)
machine.add_transition('test', source='A', dest='A', conditions=lambda: False)

model.go()
model.test()
```

**Comment by aleneum** [comment]
I close this issue since their has not been any feedback in more than 14 days. Feel free to comment anyway. I will reopen the issue if required.

**Comment by nm-libang** [comment]
> Hi!
> 
> I like "transitions", but I also had a nice experience working with another FSM framework (another language) and what is really missing for me in "transitions" is a "during" action callback.
> 
> **during Actions:** During actions are executed when a state is active, an event occurs, and no valid transition to another state is available.
> 
> I see that there is a possibility to emulate this with inner transitions with "prepare" callback, but it is not exactly the same. Is it desired to extend functionality of "transitions" with such semantic?
> 
> BR, Alex

Hi. I need something similar to catch the fact that transition was not executed due to False condition. Any idea ?
