### ISSUE TITLE
Calling next_state() does not fire any conditions 

### ISSUE THREAD

**Issue by stmezzo** [pytransitions/transitions#344]
I noticed that when using ordered transitions, calling next_state() does not seem to fire off the condition:

```python
from transitions import State, Machine
class Matter(Machine):
    def is_flammable(self):
        print('got inside here flammable')`
        return False
    def is_really_hot(self):
        print('got inside here really hot')
        return True

    def __init__(self):

        states = [
                    State(name='aaa'),
                    State(name='bbb'),
                    State(name='ccc'),
                  ]

        transitions = [
                    {'trigger': 'heat', 'source': 'aaa', 'dest': 'bbb', 'conditions': ['is_flammable']},
                    {'trigger': 'heat2', 'source': 'bbb', 'dest': 'ccc', 'conditions': ['is_really_hot']},
                ]

        Machine.__init__(self, states=states, transitions=transitions, initial='bbb')
        self.add_ordered_transitions()
```
Calling with next_state():
```python
lump = Matter()
print(lump.state)
lump.next_state()
print(lump.state)
```
Output:
```python
bbb
ccc
```

Calling with heat2():
```python
lump = Matter()
print(lump.state)
lump.heat2()
print(lump.state)
```
Output:
```python
bbb
got inside here really hot
ccc
```

As you can see, only calling with heat2() fires the condition 'is_really_hot'

**Comment by julianebeli** [comment]
Hi
From my experiments it seems that the next_state() function just picks the next state in the states list. When it reaches the end of the list it just cycles around to the beginning. It does not trigger a transition.
I don't know if this behavior is wrong or right. I assume its correct.

    lump = Matter()
    print(f"initial state: {lump.state}")
    # lump.heat() #error wrong state
    print("calling trigger 'heat2()'")
    lump.heat2()
    print(f"current state: {lump.state}")
    lump.next_state()
    print(f"called next_state(): {lump.state}")
    print("calling trigger 'heat()'")
    lump.heat()
    print(f"current state: {lump.state}")
    print("No state change!")
    lump.next_state()
    print(f"called next_state(): {lump.state}")
    lump.next_state()
    print(f"called next_state(): {lump.state}")
    lump.next_state()
    print(f"called next_state(): {lump.state}")

produces

    initial state: bbb
    calling trigger 'heat2()'
    got inside here really hot
    current state: ccc
    called next_state(): aaa
    calling trigger 'heat()'
    got inside here flammable
    current state: aaa
    No state change!
    called next_state(): bbb
    called next_state(): ccc
    called next_state(): aaa

**Comment by aleneum** [comment]
Hello @stmezzo,

sorry for the long delay. `add_ordered` transitions will create custom `next_state` events. Your previously defined transitions are not considered. You can pass `conditions` as a list to `add_ordered_transitions` which is unfortunately not mentioned in the README yet. Note that `conditions` should be either one condition or a list of `<amount of states>` conditions. Conditions will be applied in the states' order BUT start from the initial state (in your case `bbb`). 
This means replacing `self.add_ordered_transitions()` with `self.add_ordered_transitions(conditions=['is_really_hot', 'condition_for_ccc_to_aaa', 'is_flammable'])` should get you the desired behaviour.
