### ISSUE TITLE
Proposal for adding list of triggers to transition configuration

### ISSUE THREAD

**Issue by amitabhn** [pytransitions/transitions#345]
It might be a good idea to be able to add multiple triggers to the same source and destination state transition. Given that the transitions configuration list forms the core logic of the state machine, I would want it to be as concise, readable and easily understandable as possible and not make it too verbose. So instead of having to define multiple transition dicts for multiple triggers but same source and destination state (and other callbacks), it would be better to keep it centralized at one place.
Example:
`transitions = [
    { 'trigger': 'start_cmd_from_local_button', 'source': 'standby', 'dest': 'active' },
    { 'trigger': 'start_cmd_from_remote_server', 'source': 'standby', 'dest': 'active' }
]`
can be condensed into
`transitions = [
    { 'trigger': ['start_from_local_button', 'start_from_remote_server'], 'source': 'standby', 'dest': 'active' }
]`

Also, this wouldn't be too hard to implement as the Machine can be easily extended. But can this functionality be made part of the core library?

**Comment by aleneum** [comment]
Hello @amitabhn,

I do see the appeal of that but as you said its not that hard to implement yourself. You could either implement your own add_transition method like

```python
from transitions import Machine, listify
class TriggersMachine(Machine):

    def add_transition(self, trigger, source, dest, conditions=None,
                       unless=None, before=None, after=None, prepare=None, **kwargs):
        for tr in listify(trigger):
            Machine.add_transition(tr, source, dest, conditions, 
                                   unless, before, after, prepate, **kwargs)
```

or use list comprehension in your transition definitions:

```python
transitions = [{'trigger': tr, 'source': 'foo', 'dest': 'bar'} for tr in ['tr1', 'tr2', 'tr3']]
```

If you find an elegant solution which does not break extensions and also does not require major refactoring in the extension modules I look forward to your pull request for reviewing. 
I leave this issue open for a while to see if more users would be interested in that extension.

**Comment by aleneum** [comment]
Closing this since there has been no feedback for roughly 2 weeks. If you have further feedback, feel free to comment on this issue. I will reopen the issue if necessary.
