### ISSUE TITLE
Proposal to add callback if condition is not satisfied

### ISSUE THREAD

**Issue by amitabhn** [pytransitions/transitions#346]
It might be a good idea to be able to add a callback function that will be called if the given conditions could not be satisfied. This would keep the transition concise, readable and easily understandable without needing to add multiple transitions.

**Comment by aleneum** [comment]
@amitabhn,

sorry for the late answer. `finalize_event` might be what you are looking for:

```python
from transitions import  Machine


def check_event(event):
    # if event.result is False but no error occured it must
    # be because of no valid transition
    if not event.result and not event.error:
        print("Condition check failed!")


m = Machine(states=['A', 'B'], transitions=[['go', 'A', 'B']], initial='A', finalize_event=check_event, send_event=True)
m.add_transition('go', 'B', 'A', conditions=lambda x: False)
m.go()  # >>>
m.go()  # >>> Condition check failed! 
```

**Comment by aleneum** [comment]
Or you could have a look at the "during" feature proposal here (#342).

**Comment by aleneum** [comment]
I close this issue since their has not been any feedback in 14 days. Feel free to comment if this still is an issue for you. I will reopen the issue if required.
