### ISSUE TITLE
Merge two machines together

### ISSUE THREAD

**Issue by parthsharma1996** [pytransitions/transitions#347]
I currently have two machines in different files.

It is possible to _merge_ these two machines together such that I end up with a bigger machine which has the superset of all states and transitions.

Basically I want to keep these two machine modular and avoid

1. Manually copying the `states`, `transitions` etc from one file to another.
2. Importing the python module and then manually writing `self.states = machine1.states + machine2.states`. 
	- Also since I have written a lot of functions in these classes anyway I am not sure how I can "add" functions.

I did look at the solution for https://github.com/pytransitions/transitions/issues/271 
but I don't want to make the other machine a child of the first one. I want them to be of the same level.

**Comment by aleneum** [comment]
Hi @parthsharma1996,

currently there is no feature to merge two machines into one. If both of your machines have no event name collisions you could just pass the same model to both:

```python
from transitions import Machine

class Model:
    pass

model = Model()
# initial=B is just passed to prevent the creation of an 'initial' state. As models 'spawn' in their initial
# state, no exit/enter callbacks of B will be called
m1 = Machine(model, states=['B', 'C', 'D'], transitions=[['go', 'B', 'C'], ['run', 'C', 'D']], initial='B')
m2 = Machine(model, states=['A', 'B', 'C'], transitions=[['look', 'A', 'B'], ['walk', 'B', 'C']], initial='A')

assert model.is_A()
model.look()
model.walk()  # could also call model.go() here
assert model.is_C()
model.run()
assert model.is_D()
```

Writing a generic `merge` function is also not trivial and currently out of scope for `transitions` as any of the attributes (auto_transitions, send_event, prepare_event, after_state_change, before_state_change, ...) might differ. It's also unclear what to do when two states have the same name. If we ignore all that and if we assume that there is a 'base' and a 'target' machine you could merge the attributes `Machine.states` and `Machine.events` before adding models:

```
from transitions import Machine

class Model:
    pass

def merge_machines(base, target):
    base.states.update(target.states)
    base.events.update(target.events)

# add models later since merging machine would not update models
m1 = Machine(None, states=['B', 'C', 'D'], transitions=[['go', 'B', 'C'], ['run', 'C', 'D']])
m2 = Machine(None, states=['A', 'B', 'C'], transitions=[['look', 'A', 'B'], ['walk', 'B', 'C']])
merge_machines(m1, m2)

model = Model()
m1.add_model(model, initial='A')

assert model.is_A()
model.look()
model.walk()  # could also call model.go() here
assert model.is_C()
model.run()
assert model.is_D()
```

If you want to do it *on-the-fly* meaning that one machine should be 'extended' with another machine and update its models, you could have a look at the *nested* extension which copies transitions and states.

**Comment by aleneum** [comment]
I close this issue since their has not been any feedback in 14 days. Feel free to comment if this still is an issue for you. I will reopen the issue if required.
