### ISSUE TITLE
RuntimeError: this event loop is already running.

### ISSUE THREAD

**Issue by alexcrownjr** [pytransitions/transitions#348]
Hi, I'm using dev-async branch and got this error "RuntimeError: this event loop is already running."

**Comment by aleneum** [comment]
Hi @alexcrownjr,

sorry for the late answer. The implementation/api of `AsyncMachine` has changed drastically. `AsyncMachine` does not handle the event loop anymore. Feel free to give `dev-async` a second try. If you observe bugs/weird behaviour, please open another bug report.
