### ISSUE TITLE
Calculating transition based on current state

### ISSUE THREAD

**Issue by bhunwal** [pytransitions/transitions#351]
In my use case I want to calculate trigger based on current state and put that logic inside states. Is this possible by the library? currently the way I see that library works is,
lets say you are on state_1 and define what should happen if trigger_a has happened, but i what if I want to use it like

let's say I am on state_1 and input_x has come, not there is big fat business logic in state_1, which determines my target state.

**Comment by aleneum** [comment]
Hello @bhunwal,

could you provide a minimal working example for your issue? I'd say that one of the reasons to use a state machine is to NOT have a big fat business logic in states:

```python
transitions = [{'trigger': 'eventX', 'source': 'A', 'dest': 'B'},
               {'trigger': 'eventX', 'source': 'B', 'dest': 'C'},
               {'trigger': 'eventX', 'source': 'C', 'dest': 'D'}]
...
# what will happen here depends on the current state of the machine/model
# no if-then-else-logic required here. Specific behaviour is defined in on_exit, 
# on_enter state callbacks and before/after transition callbacks.
model.eventX()  
```

**Comment by aleneum** [comment]
I close this issue since their has not been any feedback in 14 days. Feel free to comment if this still is an issue for you. I will reopen the issue if required.
