### ISSUE TITLE
migrate to pytest?

### ISSUE THREAD

**Issue by artofhuman** [pytransitions/transitions#356]
Hi, @aleneum. 
What do you think can we migrate this project from `nosetests` to `pytest`?

**Comment by aleneum** [comment]
Hi @artofhuman,

>  What do you think can we migrate this project from nosetests to pytest?

I don't have a strong opinion about that. What are the major benefits of using `pytests` in contrast to nosetests? Are there any caveats?

**Comment by tyarkoni** [comment]
Nose is no longer maintained, and pytest has a lot of nice features. I'd support switching—though I believe pytest can run all of the current tests, so I don't think there's any urgency.

**Comment by artofhuman** [comment]
@aleneum I can create PR if you agree

**Comment by aleneum** [comment]
Hi @artofhuman,

> @aleneum I can create PR if you agree

sure, that would be much appreciated! I just finished working on `master` (for now).
