### ISSUE TITLE
After 0.8.0 update start getting [TypeError: 'GraphMachine' object is not callable] when changing a state.

### ISSUE THREAD

**Issue by rSrkn** [pytransitions/transitions#398]
An existing **GraphMachine**  is raising an error when changing a state.
It works OK as before 0.8.0 update if I use 
`from transitions import Machine` instead of 
`from transitions.extensions import GraphMachine as Machine`

**Transitions**:
```
        transitions = [
            {
                'trigger': 'trigger_proceed',
                'source': self.received,  # received state (initial)
                'dest': self.waiting_for_approval,
                'after': 'send_notification'  
            },
...
```

**Partial stack trace**
```
finite_state_machine.trigger_proceed()
  File "/Users/c4-m411-g5467/.local/share/virtualenvs/st-1gA9slZY/lib/python3.7/site-packages/transitions/core.py", line 390, in trigger
    return self.machine._process(func)
  File "/Users/c4-m411-g5467/.local/share/virtualenvs/st-1gA9slZY/lib/python3.7/site-packages/transitions/core.py", line 1122, in _process
    self._transition_queue[0]()
  File "/Users/c4-m411-g5467/.local/share/virtualenvs/st-1gA9slZY/lib/python3.7/site-packages/transitions/core.py", line 408, in _trigger
    return self._process(event_data)
  File "/Users/c4-m411-g5467/.local/share/virtualenvs/st-1gA9slZY/lib/python3.7/site-packages/transitions/core.py", line 417, in _process
    if trans.execute(event_data):
  File "/Users/c4-m411-g5467/.local/share/virtualenvs/st-1gA9slZY/lib/python3.7/site-packages/transitions/core.py", line 269, in execute
    self._change_state(event_data)
  File "/Users/c4-m411-g5467/.local/share/virtualenvs/st-1gA9slZY/lib/python3.7/site-packages/transitions/extensions/diagrams.py", line 29, in _change_state
    graph.set_previous_transition(self.source, self.dest)
  File "/Users/c4-m411-g5467/.local/share/virtualenvs/st-1gA9slZY/lib/python3.7/site-packages/transitions/extensions/diagrams_pygraphviz.py", line 236, in set_previous_transition
    src = self._get_global_name(src.split(self.machine.state_cls.separator))
  File "/Users/c4-m411-g5467/.local/share/virtualenvs/st-1gA9slZY/lib/python3.7/site-packages/transitions/extensions/diagrams.py", line 260, in _get_global_name
    with self.machine(state):
TypeError: 'GraphMachine' object is not callable
```

**Comment by aleneum** [comment]
Hi @rSrkn,

what is `self.received`? A string? A property? Could you provide a minimal example I can use for debugging?

**Comment by aleneum** [comment]
Okay, what I can tell so far:

you are using GraphMachine which does not support hierarchical/nested states but you somehow end up with a `NestedGraph` which expects your machine to handle nested states (and thus requires `HierarchicalMachine`)
Usually `NestedGraph` is chosen when your machine's state class has a `separator` attribute.
This condition might be a bit too relaxed. But to be able to determine this I'd more info about your (maybe custom) `State` class and how you use `GraphMachine.`

The code below works fine for me (you don't need to initialize state in advance I just did that to check whether this might be an issue).

```python
class Model:

    def __init__(self):
        self.received = State("Foo")
        self.waiting_for_approval = State("Bar")
        transitions = [
            {
                'trigger': 'trigger_proceed',
                'source': self.received,  # received state (initial)
                'dest': self.waiting_for_approval,
                'after': 'send_notification'
            }]
        self.machine = Machine(self, states=[self.received, self.waiting_for_approval],
                               transitions=transitions, initial=self.received, queued=True)

    def send_notification(self):
        print("notification sent")


model = Model()
model.trigger_proceed()
assert model.state == model.waiting_for_approval.name
```

**Comment by rSrkn** [comment]
Hi @aleneum,

Thank you for the quick response. 
You are right, even if I am not using the Nested features, I have `State.separator = '↦'`
in the model class. I removed it and it worked as expected.  Thank you!

On the other hand, after I removed the `State.separator`  the layout of the diagram image generated becomes horizontal instead of vertical. 
To overcome this, for now, I have 2 classes one inherits **Machine** and the other inherits **GraphMachine**. And use GraphMachine with `State.separator`  when generating the diagram :)
Are there any options for `get_graph / draw` to able to use the vertical layout. I could not find it from a quick scan in the source code.

**Comment by aleneum** [comment]
> On the other hand, after I removed the State.separator the layout of the diagram image generated becomes horizontal instead of vertical.

by default, 'simple' layouts are horizontal (LR) and hierarchical vertical (TB). 

> Are there any options for get_graph / draw to able to use the vertical layout. I could not find it from a quick scan in the source code.

the `GraphMachine` class has several class properties meant for Graphviz Styling:

* `GraphMachine.machine_attributes`: dict for non-nested graphs 
* `GraphMachine.hierarchical_machine_attributes`: dict for nested graphs 
* `GraphMachine.style_attributes`: defines node, graph/cluser and edge styling

Both contain Graphviz keywords which alter the final layout. If you want to use a vertical layout with `State` and `GraphMachine` you can a) alter `machine_attributes` for a machine instance or b) create a custom class:

```python
from transitions.extensions import GraphMachine

machine = GraphMachine()
assert machine.machine_attributes['rankdir'] == 'LR'
machine.machine_attributes['rankdir'] = 'TB'


class VerticalGraphMachine(GraphMachine):

    machine_attributes = {
        'directed': 'true',
        'strict': 'false',
        'rankdir': 'TB',
    }

machine = VerticalGraphMachine()
assert machine.machine_attributes['rankdir'] == 'TB'
```

For more info about Graphviz keywords you can have a look at https://www.graphviz.org/doc/info/attrs.html

Did `State.seperator` fulfill a specific purpose in your state machine?

**Comment by rSrkn** [comment]
Thanks for the detailed information.

Initially, I was testing **HierarchicalMachine** and used `State.separator = '↦'`.  After that moved to **GraphMachine** and forgot to remove the `State.separator`.
It is OK to close this issue.

Thanks again.
