### ISSUE TITLE
Support for nested states from nested Enums

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions#404]
Consider the following Enum:
```python
from enum import Enum, auto
class Foo(Enum):
  A = auto()
  B = auto()

class Bar(Enum):
  FOO = Foo
  C = auto()
```

If we were to provide `Bar` to a `HierarchicalMachine` I'd expect it to take all the items in Foo as children of the Foo state.

However this is not the case:
```
In[18]: from transitions.extensions import HierarchicalMachine
In[19]: HierarchicalMachine(states=Bar)
Out[19]: <transitions.extensions.nesting.HierarchicalMachine at 0x7f517ea75d90>
In[20]: machine = HierarchicalMachine(states=Bar)
In[21]: machine.states
Out[21]: 
OrderedDict([('FOO', <NestedState('FOO')@139987994034720>),
             ('C', <NestedState('C')@139987994035296>),
             ('initial', <NestedState('initial')@139987994035200>)])
In[22]: machine.states['FOO']
Out[22]: <NestedState('FOO')@139987994034720>
In[23]: machine.states['FOO'].states
Out[23]: OrderedDict()
```

This can be easily added if I am not wrong.

**Comment by thedrow** [comment]
@aleneum I closed this issue but documentation is still missing.
Are you going to add it?
Should I reopen?

**Comment by aleneum** [comment]
Documentation is one todo, yeah. Second todo is to check how transitions can be added from and to nested enums. As far as I can tell this does not work so far.

```python
class Foo(enum.Enum):
    A = 0
    B = 1


class Bar(enum.Enum):
    FOO = Foo
    C = 2
    D = 3


m1 = HierarchicalMachine(states=Bar, initial=Bar.C)
assert m1.is_C()
m1.add_transition('go', Bar.C, Bar.D)
m1.go()  # works
assert m1.is_D()
m1.to_FOO_A()
assert m1.is_FOO_A()

m1.add_transition('go', Foo.A, Foo.B)
# m1.add_transition('go', Bar.FOO.value.A, Bar.FOO.value.B)
m1.go()
# state = _machine.get_state(state_name)
# >>> ValueError: State '['A']' is not a registered state.
```

**Comment by thedrow** [comment]
Oh that's definitely a bug.
I guess we need to check if Foo is a child state of Bar.

**Comment by thedrow** [comment]
Actually that's also a new feature.
Right now the only way to define transitions with nested states is with strings.
If we document that, we can release and introduce this feature later.

**Comment by aleneum** [comment]
> Actually that's also a new feature.
> Right now the only way to define transitions with nested states is with strings.

The theoretically working definition with strings (by name) would be `m1.add_transition('go', 'FOO_A', 'FOO_B')`. However, that does not work either because `Foo.A` (as m1.state) is currently considered as 'A' which is not valid.
I do think the ability to define custom transitions (not just auto transitions) to enter nested enum states is a mandatory feature before nested enums can be released as it is vital for many applications.

**Comment by aleneum** [comment]
So it comes down to how to resolve enums in `_build_state_tree`. I will probably start with a brute force search and will resolve enums by searching them in the complete state tree. That should not have much impact on users not using enums.

**Comment by aleneum** [comment]
Hi @thedrow,

do you have unpublished changes in the pipe? If not, I'd go forth and **rebase** `next-state` to clean up the commit history a bit and then merge it into `master`.

**Comment by thedrow** [comment]
No, not currently.
In fact, if you can release a new version that would be awesome :smile:.

**Comment by aleneum** [comment]
feature has been implemented. Thanks again at @thedrow for your support. It lacks some features of 'ordinary' nested states (initial states for instance) but should be usable. closing this issue. If bugs occur, a separate issue should be opened.
