### ISSUE TITLE
Travis CI does not appear in PR checks

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions#408]
It's harder to contribute when you don't know the build status after you open a PR.
Please investigate.

**Comment by aleneum** [comment]
PRs are building fine (See [here](https://travis-ci.org/github/pytransitions/transitions/pull_requests)). I cannot say why they are not showing up in the PR though. I reset/revoked permissions for travis since some people report that helped. We'll see...

**Comment by aleneum** [comment]
The fact that coveralls adds the tests results is an indicator that travis correctly triggers tests. I need to figure out why it still does not add results to the PR.

**Comment by aleneum** [comment]
If you have a look at https://github.com/pytransitions/transitions/commits/next-release, you'll see that sometimes travis checks are included and sometimes not. I haven't changed a thing on the configuration. I assume that this might be related to issues on travis' end. I will close this for now. If you find an indicator that this is actually related to missing keys/misconfiguration in this repo, feel free to comment. I will reopen this issue when needed.

**Comment by thedrow** [comment]
I think you should send an email to Travis' support.
