### ISSUE TITLE
How to pass arguments to a transition?

### ISSUE THREAD

**Issue by noamzilo** [pytransitions/transitions#409]
https://stackoverflow.com/questions/60856982/python-transitions-library-how-to-pass-argumnets-to-a-transition

It is not clear to me from the doc, or I can't find it.
How do I pass an argument to a transition?

**Comment by aleneum** [comment]
Thanks for using SO first. I hope my answer will clarify things for you. I will close this issue since it does not contain a feature request or a bug report. Feel free to comment anyway. If a feature request evolves, I will reopen this issue.
