### ISSUE TITLE
Enable usage of other event loops in `AsyncMachine`

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions#420]
[AnyIO](https://anyio.readthedocs.io/en/latest/) is a library which abstracts event loops.
Currently our implementation only supports AsyncIO but trio is also a popular event loop which we can support.
AnyIO allows us to support both with ease.

I can port all of the code except these lines:
https://github.com/pytransitions/transitions/blob/9237b9e0978ad3d904d4f0e7b3d82d99a6b7e76f/transitions/extensions/asyncio.py#L125-L136

I think we should be using a [CancelScope](https://anyio.readthedocs.io/en/latest/cancellation.html) but I'm not really sure how.
Any feedback is appreciated.

**Comment by thedrow** [comment]
I don't think we should introduce a hard dependency.

Maybe an extra dependency?
Or a different package?

I need this because Celery will be using trio.

**Comment by aleneum** [comment]
I am currently attempting to decouple asyncio calls from `AsyncMachine` to make overriding easier (see [dev-trio](https://github.com/pytransitions/transitions/tree/dev-trio))
* `asyncio.iscoroutinefunction` could be replaced with `inspect.isawaitable` with minor refactoring
* calls to `asyncio.gather` have been unified to call a `AsyncMachine.await_all` instead. This should make the usage of nurseries and stuff easier. But I need to test that. 
* cancellation of running tasks has been isolated in `AsyncMachine.switch_model_context(model)`

ToDo:
* How does trio handle cancellation? `(Nested)AsyncEvent` awaits `AsyncMachine._process` and catches `asyncio.CancelledError`.

**Comment by aleneum** [comment]
I just pushed changes to `AsyncMachine` that finished the isolation of `asyncio`. `AsyncTimeout` still relies on `asyncio` though. If another async library should be used, a subclass of `AsyncMachine` needs to take care of:
* `await_all` - basically the parallel callback processing in `before`, `enter`, `exit` and such
* `process_context` - a check whether this current event trigger has been called by a currently processed event or happened in a new context
* `switch_model_context` - cancel currently processed tasks when a transition is about to happen IF these tasks are processed in another event

Based on these changes I could implement a `TrioMachine`:
```python
import trio

from transitions.extensions.asyncio import AsyncMachine


class TrioMachine(AsyncMachine):

    @staticmethod
    async def await_all(partials):
        """
        Executes callables without parameters in parallel and collects their results.
        Args:
            partials (list): A list of callable functions

        Returns:
            list: A list of results. Using asyncio, the list will be in the same order as the passed callables.
        """
        results = []
        async def with_result(func):
            results.append(await func())

        async with trio.open_nursery() as nursery:
            for par in partials:
                nursery.start_soon(with_result, par)

        return results

    async def process_context(self, func, model):
        """
        This function is called by an async event to make callbacks processed in Event._trigger cancellable.
        Using asyncio, this will result in a try-catch block catching CancelledEvents.
        Args:
            func (callable): The partial of Event._trigger with all parameters already assigned
            model (object): The currently processed model

        Returns:
            bool: returns the success state of the triggered event
        """
        if self.is_subtask.get() is False:
            with trio.CancelScope() as scope:
                self.async_tasks[model] = scope
                self.is_subtask.set(scope)
                return await func()
            self.async_tasks[model] = None
        else:
            return await func()

    def switch_model_context(self, model):
        """
        This method is called by an async transition when all conditional tests have passed and the transition will happen.
        This requires already running tasks to be cancelled.
        Args:
            model (object): The currently processed model
        """
        if self.is_subtask.get() != self.async_tasks.get(model, None):
            self.async_tasks[model].cancel()
            self.async_tasks[model] = self.is_subtask.get()

async def await_never_return():
    await trio.sleep_forever()

async def await_true():
    return True

async def fix():
    await m2.fix()

m1 = TrioMachine(states=['A', 'B', 'C'], initial='A', name="m1")
m2 = TrioMachine(states=['A', 'B', 'C'], initial='A', name="m2")
m2.add_transition(trigger='go', source='A', dest='B', before=await_never_return)
m2.add_transition(trigger='fix', source='A', dest='C', conditions=await_true)
m1.add_transition(trigger='go', source='A', dest='B', conditions=await_true, after='go')
m1.add_transition(trigger='go', source='B', dest='C', after=fix)

async def main():
    async with trio.open_nursery() as nursery:
        nursery.start_soon(m2.go)
        nursery.start_soon(m1.go)

trio.run(main)

assert m1.is_C()
assert m2.is_C()
```

**Comment by thedrow** [comment]
> * `asyncio.iscoroutinefunction` could be replaced with `inspect.isawaitable` with minor refactoring
That's the one piece of code you shouldn't need to replace.
That function is more extensive in its checks (e.g. mocks work with it but don't with `inspect.isawaitable`).

> * calls to `asyncio.gather` have been unified to call a `AsyncMachine.await_all` instead. This should make the usage of nurseries and stuff easier. But I need to test that.
Not sure how you can do that.
It's easier to replace the code with AnyIO.
> * cancellation of running tasks has been isolated in `AsyncMachine.switch_model_context(model)`
> 
> ToDo:
> 
> * How does trio handle cancellation? `(Nested)AsyncEvent` awaits `AsyncMachine._process` and catches `asyncio.CancelledError`.
Trio uses [cancel scopes](https://trio.readthedocs.io/en/stable/reference-core.html#trio.CancelScope).

**Comment by thedrow** [comment]
So you'd rather introduce trio as an optional dependency instead of using AnyIO which requires the same code as the trio version but allows you to support multiple event loops at once?

**Comment by aleneum** [comment]
> So you'd rather introduce trio as an optional dependency instead of using AnyIO which requires the same code as the trio version but allows you to support multiple event loops at once?

Haha, no. That would be indeed arguably inefficient. As I said in the beginning:

>  ... right now I'd rather stick with asyncio and maybe finding ways to enable easier customization through inheritance.

`AsyncMachine` in `dev-trio` has no dependency to `asyncio` which means it should be possible extend it with your favourite event loop. I used `trio` to illustrate how this can be done because you mentioned thats the one you mostly interested in. The `TrioMachine` however wont be -- as of today -- part of `transitions`.

**Comment by aleneum** [comment]
As far as I can tell `trio` and `asyncio` share the same syntax when it comes to executing tasks in parallel and handling cancellation. I guess a `AnyIOMachine` could roughly look like this:

```python
from anyio import create_task_group, open_cancel_scope

class AnyIOMachine(AsyncMachine):

    @staticmethod
    async def await_all(partials):
        results = []
        async def with_result(func):
            results.append(await func())

        async with create_task_group as tg:
            for par in partials:
                tg.spawn(with_result, par)

        return results

    async def process_context(self, func, model):
        if self.current_context.get() is None:
            async with open_cancel_scope() as scope:
                self.current_context.set(scope)
                return await func()
            return False
        return await func()

    def switch_model_context(self, model):
        current_scope = self.current_context.get()
        running_scope = self.async_tasks.get(model, None)
        if current_scope != running_scope:
            if running_scope is not None:
                self.async_tasks[model].cancel()
            self.async_tasks[model] = self.current_context.get()
```

Maybe `AnyIO` has some better mechanisms to get the results of callbacks (like `asyncio.gather`) but this should work nevertheless.

**Comment by aleneum** [comment]
`0.8.2` has been released. It should be possible to use `AsyncMachine` as a base for a machine used with `trio` or `anyio`. I consider this solved. Feel free to comment and I will reopen the issue when necessary.

**Comment by thedrow** [comment]
I think we can create another repository with the AnyIO implementation or provide it in this repository.

**Comment by thedrow** [comment]
The implementation has a problem which I'm trying to fix:
```python
    async def process_context(self, func, model):
        if self.current_context.get() is None:
            try:
                async with open_cancel_scope() as scope:
                    self.current_context.set(scope)
                    return await func()
            except get_cancelled_exc_class():
                return False # This should raise instead.
        return await func()
```

Your version did not catch the cancelled exception unfortunately which is why we didn't see this problem before.

We must raise the cancelled exception or [we risk undefined behavior](https://anyio.readthedocs.io/en/latest/cancellation.html#finalization).
