### ISSUE TITLE
State names being split

### ISSUE THREAD

**Issue by abhishek-sharma97** [pytransitions/transitions#425]
Using transitions 0.8.1
While creating a HeirarchicalMachine with states and transitions having "_" in the name, the split function is just picking up the first substring after the split and giving KeyError stating the substring is not found in the states dictionary
Any particular reason for adding this split? This was working perfectly with 0.7.2.

```
states = [
        {"name": "null"},
        {"name": "app_draft"},
        {"name": "validation_pending"},
        {"name": "validation_failed"},
        {"name": "ready"},
    ]
```

On further digging, realised that its happening here: https://github.com/pytransitions/transitions/blob/ddd0709af13e007c9cd8dd56fda77dbc51f90f60/transitions/extensions/nesting.py#L343

Is it because of the counter addition functionality added for children states?  Any suggestions and answers will be really appreciated.

**Comment by potens1** [comment]
Hello,

I bumped into the same problem (reusing old code with new lib version), An easy fix you can use is to change the separator with
```
NestedState.separator = '↦'
```
Hope it helps

PS: I think this will bite more than one developer...

**Comment by abhishek-sharma97** [comment]
This sorted the issue, Thanks!
