### ISSUE TITLE
pylint complains that transition methods don't exist

### ISSUE THREAD

**Issue by Bob-May** [pytransitions/transitions#426]
From readme.md

> Notice the shiny new methods attached to the Matter instance (evaporate(), ionize(), etc.). Each method triggers the corresponding transition. You don't have to explicitly define these methods anywhere; the name of each transition is bound to the model passed to the Machine initializer (in this case, lump). Additionally, there is a method called trigger now attached to your model. This method lets you execute transitions by name in case dynamic triggering is required.

example to reproduce:
```
import transitions
class myStateMachine(object):

    # Define states
    states = ['State_A', 'State_B']

    def __init__(self):

        # Initialize the state machine
        self.state = None #prevents the linter from complaining that there is no state member
        self.machine = transitions.Machine(model=self, states=self.states, initial='State_A')

        #Define Transitions
        self.machine.add_transition('to_B','State_A', 'State_B')
        self.machine.add_transition('to_A', 'State_B', 'State_A')
        
        
if __name__ == "__main__":
    
    example = myStateMachine()
    example.to_B()
    print(example.state)
```

> output>>
> State_B
> State_A

pylint complains

> Instance of 'myStateMachine' has no 'to_B' member
> Instance of 'myStateMachine' has no 'to_A' member

How to prevent these errors?

**Comment by Bob-May** [comment]
Looking through closed issues I see that fundamentally this is related to [Issue #383](https://github.com/pytransitions/transitions/issues/383)

**Comment by Panos26** [comment]
So did you came up with the solution for your example without using docstrings?

**Comment by Bob-May** [comment]
I have not made any attempt yet to prevent the issue.

So far my "solution" is to say to myself "It's not really a problem" when pylint highlights one of these items.

**Comment by shuttle1987** [comment]
Perhaps we can just tell Pylint that these are generated members if we want the false positive warning will go away? More about why this happens here: https://www.lesinskis.com/pylint-false-positives.html

**Comment by aleneum** [comment]
If silencing E1101 is all that is needed, `generated-members` in `.pylintrc` could do the trick. This will apease pylint when `generated-members=run`:

```python
"""a test"""

import transitions


class MyStateMachine:
    """A machine"""

    # Define states
    states = ['State_A', 'State_B']

    def __init__(self):

        # Initialize the state machine
        self.state = None  # prevents the linter from complaining that there is no state member
        self.machine = transitions.Machine(model=self, states=self.states, initial='State_A',
                                           auto_transitions=False)

        # Define Transitions
        self.machine.add_transition('run', 'State_A', 'State_B')
        self.machine.add_transition('go', 'State_B', 'State_A')

    def processing(self):
        """processes things"""

    def rapid_processing(self):
        """processes things... but faster!"""


def main():
    """where the action is"""
    example = MyStateMachine()
    example.run()


if __name__ == "__main__":
    main()
```

However, I am not sure how this should be automatized though. Adding all potential triggers manually is quite cumbersome. For `Machine` a list of transitions can be retrieved with:

```python
    print(", ". join(example.machine.events.keys()))
```

This will not include OTHER convenience functions such as `is_State_A` and `trigger`. They could be derived from transition and state names though. So extending on the one liner above might be all that is needed to generate a method whitelist:

```python
    whitelist = ['trigger', 'state']
    whitelist.extend(example.machine.events.keys())
    for s in example.machine.states:
        whitelist.append(f'is_{s}')
    print(",".join(whitelist))  # >>> trigger,state,run,go,is_State_A,is_State_B
```

**Comment by aleneum** [comment]
Closing this due to the lack of feedback. If you have more to add to that issue, feel free to comment. I will reopen the issue if necessary.
