### ISSUE TITLE
Using parallel states in "HierarchicalGraphMachine" raise  KeyError: 'parallel'

### ISSUE THREAD

**Issue by xiaohuihui1024** [pytransitions/transitions#428]
Hello, @aleneum 
I found some bugs in the Hierarchical extension in version 0.8.x.
Mainly involves enumeration, graphics, state separator.
Some combinations will cause the HSM not to work properly.

One of the issues is as follows:

```python
# works fine

# from transitions.extensions import HierarchicalGraphMachine as Machine
from transitions.extensions import HierarchicalMachine as Machine
from transitions.extensions.nesting import NestedState
NestedState.separator = '↦'
import logging
extra_args = dict(auto_transitions=False,)
states = ["A","B","C",
          {'name': "D", 'parallel': ["D_A", "D_B"],}
         ]
logging.basicConfig(level=logging.INFO)
machine = Machine(states=states, initial='A', **extra_args)
```

The above code using `HierarchicalMachine` works fine.
When using `HierarchicalGraphMachine`, it does not work properly
Note: Whether `NestedState.separator = '↦'` is executed or not, it is still the result

```python
# error

from transitions.extensions import HierarchicalGraphMachine as Machine
# from transitions.extensions import HierarchicalMachine as Machine
from transitions.extensions.nesting import NestedState
NestedState.separator = '↦'
import logging
extra_args = dict(auto_transitions=False, use_pygraphviz=False, show_conditions=False, show_state_attributes=True,)
# extra_args = dict(auto_transitions=False,)
states = ["A","B","C",
          {'name': "D", 'parallel': ["D_A", "D_B"],}
         ]

logging.basicConfig(level=logging.INFO)
machine = Machine(states=states, initial='A', **extra_args)
```

<pre><span>---------------------------------------------------------------------------</span>
<span>KeyError</span>                                  Traceback (most recent call last)
<span>&lt;ipython-input-18-026c4cb2adbd&gt;</span> in <span>&lt;module&gt;</span>
<span>     11</span> 
<span>     12</span> logging<span>.</span>basicConfig<span>(</span>level<span>=</span>logging<span>.</span>INFO<span>)</span>
<span>---&gt; 13</span><span> </span>machine <span>=</span> Machine<span>(</span>states<span>=</span>states<span>,</span> initial<span>=</span><span>'A'</span><span>,</span> <span>**</span>extra_args<span>)</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\diagrams.py</span> in <span>__init__</span><span>(self, *args, **kwargs)</span>
<span>    148</span> 
<span>    149</span>         _LOGGER<span>.</span>debug<span>(</span><span>"Using graph engine %s"</span><span>,</span> self<span>.</span>graph_cls<span>)</span>
<span>--&gt; 150</span><span>         </span>_super<span>(</span>GraphMachine<span>,</span> self<span>)</span><span>.</span>__init__<span>(</span><span>*</span>args<span>,</span> <span>**</span>kwargs<span>)</span>
<span>    151</span> 
<span>    152</span>         <span># for backwards compatibility assign get_combined_graph to get_graph</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\markup.py</span> in <span>__init__</span><span>(self, *args, **kwargs)</span>
<span>     26</span>                 self<span>.</span>_add_markup_model<span>(</span>m<span>)</span>
<span>     27</span>         <span>else</span><span>:</span>
<span>---&gt; 28</span><span>             </span>super<span>(</span>MarkupMachine<span>,</span> self<span>)</span><span>.</span>__init__<span>(</span><span>*</span>args<span>,</span> <span>**</span>kwargs<span>)</span>
<span>     29</span>             self<span>.</span>_markup<span>[</span><span>'before_state_change'</span><span>]</span> <span>=</span> <span>[</span>x <span>for</span> x <span>in</span> <span>(</span>rep<span>(</span>f<span>)</span> <span>for</span> f <span>in</span> self<span>.</span>before_state_change<span>)</span> <span>if</span> x<span>]</span>
<span>     30</span>             self<span>.</span>_markup<span>[</span><span>'after_state_change'</span><span>]</span> <span>=</span> <span>[</span>x <span>for</span> x <span>in</span> <span>(</span>rep<span>(</span>f<span>)</span> <span>for</span> f <span>in</span> self<span>.</span>before_state_change<span>)</span> <span>if</span> x<span>]</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\nesting.py</span> in <span>__init__</span><span>(self, *args, **kwargs)</span>
<span>    337</span>         self<span>.</span>_stack <span>=</span> <span>[</span><span>]</span>
<span>    338</span>         self<span>.</span>scoped <span>=</span> self
<span>--&gt; 339</span><span>         </span>_super<span>(</span>HierarchicalMachine<span>,</span> self<span>)</span><span>.</span>__init__<span>(</span><span>*</span>args<span>,</span> <span>**</span>kwargs<span>)</span>
<span>    340</span> 
<span>    341</span>     <span>def</span> __call__<span>(</span>self<span>,</span> to_scope<span>=</span><span>None</span><span>)</span><span>:</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\core.py</span> in <span>__init__</span><span>(self, model, states, initial, transitions, send_event, auto_transitions, ordered_transitions, ignore_invalid_triggers, before_state_change, after_state_change, name, queued, prepare_event, finalize_event, model_attribute, **kwargs)</span>
<span>    572</span> 
<span>    573</span>         <span>if</span> model<span>:</span>
<span>--&gt; 574</span><span>             </span>self<span>.</span>add_model<span>(</span>model<span>)</span>
<span>    575</span> 
<span>    576</span>     <span>def</span> add_model<span>(</span>self<span>,</span> model<span>,</span> initial<span>=</span><span>None</span><span>)</span><span>:</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\diagrams.py</span> in <span>add_model</span><span>(self, model, initial)</span>
<span>    214</span>                 <span>raise</span> AttributeError<span>(</span><span>'Model already has a get_graph attribute. Graph retrieval cannot be bound.'</span><span>)</span>
<span>    215</span>             setattr<span>(</span>mod<span>,</span> <span>'get_graph'</span><span>,</span> partial<span>(</span>self<span>.</span>_get_graph<span>,</span> mod<span>)</span><span>)</span>
<span>--&gt; 216</span><span>             </span>_ <span>=</span> mod<span>.</span>get_graph<span>(</span>title<span>=</span>self<span>.</span>title<span>,</span> force_new<span>=</span><span>True</span><span>)</span>  <span># initialises graph</span>
<span>    217</span> 
<span>    218</span>     def add_states(self, states, on_enter=None, on_exit=None,

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\diagrams.py</span> in <span>_get_graph</span><span>(self, model, title, force_new, show_roi)</span>
<span>    176</span>     <span>def</span> _get_graph<span>(</span>self<span>,</span> model<span>,</span> title<span>=</span><span>None</span><span>,</span> force_new<span>=</span><span>False</span><span>,</span> show_roi<span>=</span><span>False</span><span>)</span><span>:</span>
<span>    177</span>         <span>if</span> force_new<span>:</span>
<span>--&gt; 178</span><span>             </span>grph <span>=</span> self<span>.</span>graph_cls<span>(</span>self<span>,</span> title<span>=</span>title <span>if</span> title <span>is</span> <span>not</span> <span>None</span> <span>else</span> self<span>.</span>title<span>)</span>
<span>    179</span>             self<span>.</span>model_graphs<span>[</span>model<span>]</span> <span>=</span> grph
<span>    180</span>             <span>try</span><span>:</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\diagrams_graphviz.py</span> in <span>__init__</span><span>(self, *args, **kwargs)</span>
<span>    126</span>     <span>def</span> __init__<span>(</span>self<span>,</span> <span>*</span>args<span>,</span> <span>**</span>kwargs<span>)</span><span>:</span>
<span>    127</span>         self<span>.</span>_cluster_states <span>=</span> <span>[</span><span>]</span>
<span>--&gt; 128</span><span>         </span>_super<span>(</span>NestedGraph<span>,</span> self<span>)</span><span>.</span>__init__<span>(</span><span>*</span>args<span>,</span> <span>**</span>kwargs<span>)</span>
<span>    129</span> 
<span>    130</span>     <span>def</span> set_previous_transition<span>(</span>self<span>,</span> src<span>,</span> dst<span>,</span> key<span>=</span><span>None</span><span>)</span><span>:</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\diagrams_graphviz.py</span> in <span>__init__</span><span>(self, machine, title)</span>
<span>     37</span>     <span>def</span> __init__<span>(</span>self<span>,</span> machine<span>,</span> title<span>=</span><span>None</span><span>)</span><span>:</span>
<span>     38</span>         self<span>.</span>reset_styling<span>(</span><span>)</span>
<span>---&gt; 39</span><span>         </span>_super<span>(</span>Graph<span>,</span> self<span>)</span><span>.</span>__init__<span>(</span>machine<span>,</span> title<span>)</span>
<span>     40</span> 
<span>     41</span>     <span>def</span> set_previous_transition<span>(</span>self<span>,</span> src<span>,</span> dst<span>,</span> key<span>=</span><span>None</span><span>)</span><span>:</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\diagrams.py</span> in <span>__init__</span><span>(self, machine, title)</span>
<span>    239</span>         self<span>.</span>fsm_graph <span>=</span> <span>None</span>
<span>    240</span>         self<span>.</span>roi_state <span>=</span> <span>None</span>
<span>--&gt; 241</span><span>         </span>self<span>.</span>generate<span>(</span>title<span>)</span>
<span>    242</span> 
<span>    243</span>     <span>def</span> _convert_state_attributes<span>(</span>self<span>,</span> state<span>)</span><span>:</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\diagrams_graphviz.py</span> in <span>generate</span><span>(self, title, roi_state)</span>
<span>     93</span>             state_names <span>+=</span> <span>[</span>k <span>for</span> k<span>,</span> style <span>in</span> self<span>.</span>custom_styles<span>[</span><span>'node'</span><span>]</span><span>.</span>items<span>(</span><span>)</span> <span>if</span> style<span>]</span>
<span>     94</span>             states <span>=</span> _filter_states<span>(</span>states<span>,</span> state_names<span>,</span> self<span>.</span>machine<span>.</span>state_cls<span>)</span>
<span>---&gt; 95</span><span>         </span>self<span>.</span>_add_nodes<span>(</span>states<span>,</span> fsm_graph<span>)</span>
<span>     96</span>         self<span>.</span>_add_edges<span>(</span>transitions<span>,</span> fsm_graph<span>)</span>
<span>     97</span>         setattr<span>(</span>fsm_graph<span>,</span> <span>'draw'</span><span>,</span> partial<span>(</span>self<span>.</span>draw<span>,</span> fsm_graph<span>)</span><span>)</span>

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\diagrams_graphviz.py</span> in <span>_add_nodes</span><span>(self, states, container, prefix, default_style)</span>
<span>    152</span>                         root<span>.</span>node<span>(</span>name <span>+</span> <span>"_anchor"</span><span>,</span> shape<span>=</span><span>'point'</span><span>,</span> fillcolor<span>=</span><span>'black'</span><span>,</span> width<span>=</span>width<span>)</span>
<span>    153</span>                     self._add_nodes(state['children'], sub, default_style='parallel' if is_parallel else 'default',
<span>--&gt; 154</span><span>                                     prefix=prefix + state['name'] + self.machine.state_cls.separator)
</span><span>    155</span>             <span>else</span><span>:</span>
<span>    156</span>                 style <span>=</span> self<span>.</span>custom_styles<span>[</span><span>'node'</span><span>]</span><span>[</span>name<span>]</span> <span>or</span> default_style

<span>C:\Anaconda\Lib\site-packages\transitions-0.8.1-py3.7.egg\transitions\extensions\diagrams_graphviz.py</span> in <span>_add_nodes</span><span>(self, states, container, prefix, default_style)</span>
<span>    155</span>             <span>else</span><span>:</span>
<span>    156</span>                 style <span>=</span> self<span>.</span>custom_styles<span>[</span><span>'node'</span><span>]</span><span>[</span>name<span>]</span> <span>or</span> default_style
<span>--&gt; 157</span><span>                 </span>container<span>.</span>node<span>(</span>name<span>,</span> label<span>=</span>label<span>,</span> <span>**</span>self<span>.</span>machine<span>.</span>style_attributes<span>[</span><span>'node'</span><span>]</span><span>[</span>style<span>]</span><span>)</span>
<span>    158</span> 
<span>    159</span>     <span>def</span> _add_edges<span>(</span>self<span>,</span> transitions<span>,</span> container<span>,</span> prefix<span>=</span><span>''</span><span>)</span><span>:</span>

<span>KeyError</span>: 'parallel'

</pre>

When replacing `parallel` with `children` the second piece of code works fine.

```python
# works fine
from transitions.extensions import HierarchicalGraphMachine as Machine
# from transitions.extensions import HierarchicalMachine as Machine
from transitions.extensions.nesting import NestedState
NestedState.separator = '↦' 
import logging
extra_args = dict(auto_transitions=False, use_pygraphviz=False, show_conditions=False, show_state_attributes=True,)
# extra_args = dict(auto_transitions=False,)
states = ["A","B","C",
          {'name': "D", 'children': ["D_A", "D_B"],}
         ]

logging.basicConfig(level=logging.INFO)
machine = Machine(states=states, initial='A', **extra_args)
```

Maybe **the combination of** **‘parallel’** and **‘Graph’** caused this problem

**Comment by camisatx** [comment]
I experienced the same `KeyError: 'parallel'` issue described here when using the LockedHierarchicalGraphMachine.

The solution was installing pygraphviz via: `pip install pygraphviz`

Of course, this was easier said than done, requiring `pip install wheel` and `sudo apt install libgraphviz-dev`[1] before running `pip install pygraphviz`.

[1] https://stackoverflow.com/a/42315670

**Comment by aleneum** [comment]
Hi @xiaohuihui1024 and @camisatx,

this is a bug where a) `graphviz` could not resolve the correct 'parallel' styling since it was located at the wrong location and b) `pygraphviz` ignored it entirely. Running @xiaohuihui1024's code with 0.8.2 results in this:

![parallel](https://user-images.githubusercontent.com/205986/84499730-6dd4af80-acb3-11ea-8047-5f1833e118bc.png)
