### ISSUE TITLE
Slow while declaring in Loop

### ISSUE THREAD

**Issue by Gauraviitkgp** [pytransitions/transitions#434]
Hi, I've like 100,000 instaces of a class each which is calling the machine. 

```
class Matter(object):
    pass

machine = Machine(states=states, transitions=transitions, initial='Healthy')

print("At End:",timeit.time.process_time())
for i in range(100000):
	lump = Matter()
	machine = Machine(lump, states=states, transitions=transitions, initial='Healthy')
print("At End:",timeit.time.process_time())
```
This process takes around 28 seconds to complete which is kinda slowing things up. Is there any faster way to do it? If we do by Machine.add_model() it takes 
```
machine = Machine(states=states, transitions=transitions, initial='Healthy')
lump=[]
print("At End:",timeit.time.process_time())
for i in range(100000):
	lump.append(Matter())
print("At End:",timeit.time.process_time())	
machine.add_model(lump)
print("At End:",timeit.time.process_time())
```
This Takes around 79 seconds. Any suggestions on how to speed up?

**Comment by noelwilsondel** [comment]
I'm also having this issue is this expected or is this slowness a new possible issue?

**Comment by noelwilsondel** [comment]
@Gauraviitkgp incase you haven't seen it there is some excellent information in this issue: https://github.com/pytransitions/transitions/issues/146

I'm currently trying to solve my issues using some of those techniques but am curious to know if this is a possible regression.

Thanks for this library I want to find a solution so we can use it as I think it's great.

**Comment by noelwilsondel** [comment]
I also took a trick from aleneum in #146 and if we change the models list to a set the computation time drastically decreases for you example, would it be possible to update this in the project (I'm happy to make a PR).

```
class Matter(object):
    pass

machine = Machine(states=states, transitions=transitions, initial='Healthy')


class SetWrapper(set):
    def append(self, item):
        self.add(item)

machine.models = SetWrapper()

lump=[]
print("At End:",timeit.time.process_time())
for i in range(100000):
	lump.append(Matter())
print("At End:",timeit.time.process_time())	
machine.add_model(lump)
print("At End:",timeit.time.process_time())
```

**Comment by Gauraviitkgp** [comment]
Yes, it seems to fasten up things a lot, it's now nearly 5.23 seconds. Disabling auto transitions is reduces it to further 4.23 seconds which seems to reduce load massively. I'll update this to my project. Should I consider this as an official solution and close the issue?

**Comment by aleneum** [comment]
You might also want to have a look at the [Frequently Asked Questions](https://github.com/pytransitions/transitions/blob/master/examples/Frequently%20asked%20questions.ipynb).
What makes thinks slow is the dynamic decoration of models. If you do not need all the bells ans whistles have a look at [transitions memory footprint is too large for my Django app and adding models takes too long](https://render.githubusercontent.com/view/ipynb?commit=f7cc995c4e088974d49371d9583d9bcb3f2a731d&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f70797472616e736974696f6e732f7472616e736974696f6e732f663763633939356334653038383937346434393337316439353833643962636233663261373331642f6578616d706c65732f4672657175656e746c7925323061736b65642532307175657374696f6e732e6970796e62&nwo=pytransitions%2Ftransitions&path=examples%2FFrequently+asked+questions.ipynb&repository_id=25131903&repository_type=Repository#transitions-memory-footprint-is-too-large-for-my-Django-app-and-adding-models-takes-too-long.). Unfortunately, anchors do not work well in Jupyter Notebooks so you might need to scroll a bit.

```python
from transitions import Machine
from functools import partial
import timeit


class Model:

    machine = Machine(model=None, states=['A', 'B', 'C'], initial=None,
                      transitions=[
                          {'trigger': 'go', 'source': 'A', 'dest': 'B', 'before': 'before'},
                          {'trigger': 'check', 'source': 'B', 'dest': 'C', 'conditions': 'is_large'},
                      ])

    def __init__(self):
        self.state = 'A'

    @staticmethod
    def is_large(value=0):
        return value > 9000

    @staticmethod
    def before():
        print('before called')

    def __getattribute__(self, item):
        try:
            return super(Model, self).__getattribute__(item)
        except AttributeError:
            if item in self.machine.events:
                return partial(self.machine.events[item].trigger, self)
            raise


lump = []
start_time = timeit.time.process_time()
print("At Start:", start_time)
for i in range(100000):
    lump.append(Model())
end_time = timeit.time.process_time()
print("At End:", end_time)
print(f"Adding models took {end_time - start_time} seconds")
# testing triggers
lump[0].go()
assert lump[0].state == 'B'
assert lump[1].state == 'A'
```

On my notebook, this results in:

```
At Start: 0.859375
At End: 1.03125
Adding models took 0.171875 seconds
before called
```

So, the trick is to NOT add models to a machine and only use a class machine to handle all the transition logic. This way models are not decorated but can be triggered nevertheless. The downside is that you need to manage a collection of your models yourself and it lacks some convenience. However, if you are willing to extend `__getattribute__`, you can get some of it back. As already pointed out, a set can be used to increase lookup speed for your self-maintained models.

**Comment by noelwilsondel** [comment]
I'll have a go at implementing a similar solution to the example above, thanks for that @aleneum!

**Comment by Gauraviitkgp** [comment]
Hi thanks, @aleneum this works like a charm, sorry I thought the FAQ was specific to Django (maybe you can modify the heading a bit). One doubt which I had is, declaring exactly as you mentioned, the machine events are limited to 
```
{'to_A': <Event('to_A')@3108771889224>, 'to_B': <Event('to_B')@3108774810120>, 'to_C': <Event('to_C')@3108774810512>, 'go': <Event('go')@3108774810680>, 'check': <Event('check')@3108774810904>}
```
is there any way to include .is_A() as an event.
