### ISSUE TITLE
Examples of exporting a transition model as json or YAML.

### ISSUE THREAD

**Issue by pdcoded** [pytransitions/transitions#443]
Is there any example that we can refer to the export of an FSM model as a JSON or YAML. And loading it back from JSON/YAML. 

A simple example would help as there is a lot of prev. issues raised around it.

**Comment by aleneum** [comment]
Hi @pdcoded,

I hope the section "How do I load/save state machine configurations with json/yaml" in the [FAQ](https://github.com/pytransitions/transitions/blob/master/examples/Frequently%20asked%20questions.ipynb) section helps.

**Comment by pdcoded** [comment]
Perfect - Thank you @aleneum
