### ISSUE TITLE
Support enums which are already an instance of State class

### ISSUE THREAD

**Issue by chrko** [pytransitions/transitions#447]
I like to use enums which itself are based on the (custom) state class of the transition machine, e.g.

```python
class States(CustomState, enum.Enum):
    STATE1 = ('custom_constructor_arg1', 'custom_constructor_arg2', …)
    ...
```

This currently breaks at https://github.com/pytransitions/transitions/blob/3a17f8fb451f22061c775f771417d8b6f3bc396c/transitions/core.py#L769 because we assume enums are also only strings, but they can be more.

It should be enough to test before if `state` is already an instance of `self.state_cls`. I have monkey patched the method and it works for me:
```python
…
            if not isinstance(state, self.state_cls):
                if isinstance(state, (string_types, Enum)):
                    state = self._create_state(
                        state, on_enter=on_enter, on_exit=on_exit,
                        ignore_invalid_triggers=ignore, **kwargs)
                elif isinstance(state, dict):
                    if 'ignore_invalid_triggers' not in state:
                        state['ignore_invalid_triggers'] = ignore
                    state = self._create_state(**state)
…
```

**Comment by aleneum** [comment]
Hi @chrko,

that sounds like quite some corner case but for HSMs its basically just some reordering of the type checks. For `core` its one additional check though. I created a feature branch [feature-state-check](https://github.com/pytransitions/transitions/tree/feature-state-check) and will wait for some further feedback from the community. If there is no objection I will merge these changes into master before the next release.

**Comment by chrko** [comment]
Ah, perfect. I haven't checked HSM yet. :/

The test case you added test inherits from dict. I think we should add a test case which tests explicit `class States(State, enum.Enum)` or `class States(CustomState, enum.Enum)`. I will experiment until next weekend and post a patch.

**Comment by chrko** [comment]
Ah, perfect. I haven't checked HSM yet. :/

The test case you added test inherits from dict. I think we should add a test case which tests explicit `class States(State, enum.Enum)` or `class States(CustomState, enum.Enum)`. I will experiment until next weekend and post a patch.

**Comment by aleneum** [comment]
> I think we should add a test case which tests explicit class States(State, enum.Enum) [...]  I will experiment until next weekend and post a patch.

I added a test for enums as well. Let me know if it is missing something.

**Comment by chrko** [comment]
Would you like to open a PR? It's easier to comment code there.

I would propose the following test (not run yet). I don't see the need to do https://github.com/pytransitions/transitions/commit/f12936e1e28329c09aafa9ca18e2b9d3312fa7a4#diff-5b8348999e31cf2e76ed1795499f89d2R146 to get the state.
```python
    def test_custom_enum_state(self):

        class CustomStates(self.machine_cls.state_cls, enum.Enum):
            A = 'A'
            B = 'B'

        m = self.machine_cls(states=CustomStates, transitions=[['go', CustomStates.A, CustomStates.B]],
                             initial=CustomStates.A)
        m.go()
        self.assertTrue(m.is_B())
```

**Comment by aleneum** [comment]
Okay, so this is basically like how you would use enums as well. What's the benefit of letting `CustomState` inherit from `State` here?

**Comment by aleneum** [comment]
Hmm, so supporting states derived from Enum also requires changes to `HierarchicalMachine.add_transition`. It's feasible but I am not certain if it actually adds to `transitions` versatility. @chrko: Could you eloborate what the benefit of having states inherit from Enum is? Considering you former test/usage example I'd argue that this could be achieved with basic Enums as well.

**Comment by chrko** [comment]
Maybe instead of presenting an abstract use case, I'll show you my current usage and what I have changed by monkey patching: https://github.com/bermudafunk/dispatcher/commit/7d4866be13e32319a062f63e16f5e8f500559206#diff-e17bdf854e06dcb1d01a75a1f840acb9 Every usage of pytransitions is in the `dispatcher` package in this repository.
I want to adapt my usage of enums further and eliminating the additional `.value`.

As a side note: I currently switching between Python and Java a lot, so this might be not the pythonic way to go.

**Comment by aleneum** [comment]
Hi @chrko,

just a short update: I had a look at your code a while ago and I see what you are trying to achieve. I cannot really tell if there is a better way to do it. I haven't had time to wrap my head around the duality of Enum and State long enough to figure out how to solve this 'duck typing style' without the need to introduce more checks (which I like to avoid since this use case is quite special and imho changes should only have a marginal influence on more generic applications). I cannot really give you a reliable ETA but will keep this issue open as a reminder.

**Comment by aleneum** [comment]
This became quite stale and as mentioned in  #448 I did not come up with an elegant solution to process "EnumStates" without additional checks in "more common" workflows. I will close this issue for now but feel free to comment or add suggestions about how this could be treated.
