### ISSUE TITLE
how to recover a state from where it enters?

### ISSUE THREAD

**Issue by EricJin101** [pytransitions/transitions#451]
For instance, we got
states = ['Offline', 'Idle', 'Error', {'name': 'Work', 'children': ['Running', 'Stop']}]

transitions = [['login', 'Offline', 'Idle'], ['work', 'Idle', 'Work'], ...., ['error' , '*', 'Error'], ['recover', 'Error', '*']]

A (triger.error) -> Error (triger.recover) -> A
B (triger.error) -> Error (triger.recover) -> B
C (triger.error) -> Error (triger.recover) -> C
can I recover an Error state from where it enters?

**Comment by aleneum** [comment]
Hello @EricJin101,

I am not sure I get your problem correctly but you can process an event in an `on_enter_<state>` callback and decide what to do next. If you need the current event to determine actions, you can pass `send_event=True` to the constructor. For instance:

```python
from transitions import Machine

class Model:

    def on_enter_Error(self, event_data):
        source_name = event_data.transition.source
        print(f"Error occurred. Transitioned from State {source_name}. Will transition back.")
        self.trigger(f'to_{source_name}')


model = Model()
machine = Machine(model, states=['A', 'B', 'C', 'Error'], transitions=[['error', '*', 'Error']],
                  initial='A', send_event=True)
assert model.is_A()
assert model.to_B()
assert model.error()  >>> Error occured. Transitioned from State B. Will transition back.
assert model.is_B()
```

Note that this will trigger `before`, `exit_Error`, `enter_B`, `after` for the leaving transition before enter_Error is completed. You can pass `queued=True` to the constructor if you want finish `on_enter_Error` first. For more details, refer to the [README](https://github.com/pytransitions/transitions/blob/master/README.md).

**Comment by aleneum** [comment]
Since there has been no feedback for quite a while I will close this issue. Feel free to comment though. I will reopen the issue if a feature request or a bug report arises.
