### ISSUE TITLE
Initial as Tuple for Hierarchical State Machine

### ISSUE THREAD

**Issue by jaapaap79** [pytransitions/transitions#455]
I'm using pytransitions in combination with a simple store that is triggered by on_enter. It stores down the current state model and some reference data. So far I haven't used it in HSM mode, but I now have a use-case for this.

Unfortunately after I store down the state (which is a list now), I'm not really sure how to recreate the machine from it in that original state as ```initial``` doesn't take a list or a Tuple.

Perhaps it would be possible to support a Tuple of strings to allow this use-case?

**Comment by aleneum** [comment]
Hello @jaapaap79,

> Perhaps it would be possible to support a Tuple of strings to allow this use-case?

Do you want to initialize a machine in a parallel state? If not: Could you provide an example of what you try to achieve.

**Comment by jaapaap79** [comment]
Yes, exactly, initialize in parallel state.

**Comment by aleneum** [comment]
This has been implemented in 0.8.4. You can pass lists (and tuples)  now to `initial` in an HSM constructor. If you face issues using that feature, please file a new bug with a detailled error description.
