### ISSUE TITLE
Reuse of previously created HSMs : child machine on_enter and on_exit function

### ISSUE THREAD

**Issue by alexandretanem** [pytransitions/transitions#457]
Hello,
Wouldn't it be interesting to have `enter` and `exit` callbacks on a HierarchicalStateMachine (or even a Machine) ? 
With the [Reuse of previously created HSMs](https://github.com/pytransitions/transitions#reuse-of-previously-created-hsms) functionality, it would allow the reused machine to detect entry into one of its states. 

Here is an example :
```python
from transitions.extensions import HierarchicalGraphMachine as Machine

class Child(Machine):

    def __init__(self):
        states = ['init','success', 'error']
        super(Machine,self).__init__(states=states, initial="init")
        self.add_transition('good','init','success', after=self.action)
        self.add_transition('bad','init','error', after=self.action)

    def action(self):
        print('Action from child')

    def on_enter(self):
        print('Entering child machine')

    def on_exit(self):
        print('Exiting child machine')



class Parent(Machine):

    def __init__(self, child):

        states = ['init',
                  {'name':'child', 'children':child},
                  'done']
        super(Machine, self).__init__(states=states, initial="init")
        self.add_transition('go', 'init', 'child')
        self.add_transition('finish', 'child','done')


if __name__ == "__main__":

    c = Child()
    p = Parent(c)

    p.go()
    # Entering child machine
    p.good()
    # Action from child
    p.finish()
    # Exiting child machine
```

I thought of workarounds to reproduce approximately the example, but it would not really achieve the desired behaviour : 
- setting `on_enter` and `on_exit` on the `child` state of the Parent SM as described [in the Readme](https://github.com/pytransitions/transitions/#callbacks)
    - Parent state has to be aware of internal methods Child the state machine, it is not "transparent" to the Parent SM
- setting `on_enter` and `on_exit` on each state of the Child SM
    - It is not practical
    - It is impossible to predict from which state we will be or entering leaving the state machine

**Comment by aleneum** [comment]
Hi @alexandretanem,

interesting idea. As you mentioned yourself this behaviour can already be enabled via `p.on_enter_child(c.on_enter)`. As a remark you addedd:

> Parent state has to be aware of internal methods Child the state machine, it is not "transparent" to the Parent SM

If we try to imagine how this could be implemented somewhere in `transitions`, we see that at some point we do have to check or 'guess' that a nested machine has 'on_enter/exit' methods. We can do the same in overrides as well.

```python
from transitions.extensions import HierarchicalGraphMachine as Machine
from transitions.core import listify


class Child(Machine):

    def __init__(self):
        states = ['init','success', 'error']
        super(Machine,self).__init__(states=states, initial="init")
        self.add_transition('good','init','success', after=self.action)
        self.add_transition('bad','init','error', after=self.action)

    def action(self):
        print('Action from child')

    def on_enter(self):
        print('Entering child machine')

    def on_exit(self):
        print('Exiting child machine')



class Parent(Machine):

    def __init__(self, child):

        states = ['init',
                  {'name':'child', 'children':child},
                  'done']
        super(Machine, self).__init__(states=states, initial="init")
        self.add_transition('go', 'init', 'child')
        self.add_transition('finish', 'child','done')

    def add_states(self, states, on_enter=None, on_exit=None,
                   ignore_invalid_triggers=None, **kwargs):
        states = listify(states)
        super(Parent, self).add_states(states, on_enter, on_exit, ignore_invalid_triggers, **kwargs)
        for state in states:
            if isinstance(state, dict):
                child = state.get('children', None)
                if isinstance(child, Machine):
                    nested = self.get_state(state['name'])
                    if hasattr(child, 'on_enter'):
                        nested.add_callback('enter', getattr(child, 'on_enter'))
                    if hasattr(child, 'on_exit'):
                        nested.add_callback('exit', getattr(child, 'on_exit'))

if __name__ == "__main__":

    c = Child()
    p = Parent(c)

    p.go()
    # Entering child machine
    p.good()
    # Action from child
    p.finish()
    # Exiting child machine
```

If you have a more elegant solution in mind, let me know.

**Comment by alexandretanem** [comment]
This is also the way I thought to do it most easily. 

I also thought it could be interesting to add the possibility to do it at initialization :
```python
def printHello():
    print("Hello entering")

states = ['init','done']
machine = HierarchicalMachine(states=states, initial='init', on_enter=printHello)
```

The solutions proposed is perfect for HSM, it could be nice to integrate it :+1:  
but I just asked myself the question about stand alone machines ? e.g. we want to control directly c = Child() of the example. 

If we use `c` as a reused SM, `on_enter` and `on_exit` will be be called, but they won't if `c` is used as a stand-alone machine. Couldn't there be a more generic way to allow calling these callbacks for any Machine class, reused or not? 
Indeed important functionalities could be implemented in these callbacks, for example in a SM initially thought of as a "reused machine", we could later want to use it as a stand alone machine.

- for `on_exit`, a stand-alone machine is always in one of its states, it never leaves them so it wouldn't really make sense to have it
- for `on_enter`, maybe it just could juste be called in `__init__` for example
For both, I think it would make no sense to consider the case of stand-alone SM unless we define a new attribute on `Machine` : a "running" attribute. This might (maybe?) involve defining a run () method on the Machine in `transitions`, which did not seem to be desired #36

In the readme, in [Reuse of previously created HSMs](https://github.com/pytransitions/transitions#reuse-of-previously-created-hsms)
> However, since 0.8.0 states are just referenced which means changes in one machine's states will influence the other instance.

When I first read this I thought that a Parent having `.state` in one of the child state would influence the child instance in the sense that : `p.state == "child_success" ⇒(implies) c.state == "success"` but this is not the case. 
There maybe here another way to implement `on_enter` and `on_exit` on the main `Machine` class using these two ideas : 
- A `Machine` is self-aware that it is running or not
- A child machine instance state is influenced by its parent machine. When we enter one of the states of the child SM, it "takes the control" in the sense that the parent machine will forward trigger calls to the child. For example : when p.state == "child_init", calling `p.good()` would imply `p` to call `c.good()`  



This is maybe a pretty big change in the way HSMs are designed so I don't know if it's worth it, only to add on_enter and on_exit on "stand-alone" machines

**Comment by aleneum** [comment]
Hi @alexandretanem,

> However, since 0.8.0 states are just referenced which means changes in one machine's states will influence the other instance.

this requires some wording improvement, I agree.

> when we enter one of the states of the child SM, it "takes the control"  [...] calling p.good() would imply p to call c.good()

I think the notion of thinking of a nested state as a nested machine is valid and broadly speaking this is how SCXML wants HSMs to be implemented in my understanding (one machine just passing the scope to another machine). `transitions` works a bit different though: It is the model that is the stateful object and it is also the model that defines the callbacks. If no model is specified, the machine will act as a model but you could pass any object to be the model in `transitions`. The connection of model and (lazy) callbacks (and the decoupling of state, callbacks and machine) is 'by design'. The nesting machine does not know anything about models managed by the nested machine. It just copies event and transition information (by reference as much as possible). One could also add the models to each substate and check for callbacks when there is no fitting callback (or even prioritize callbacks of child models). Models need to be aware of that and treat 'self' accordingly or otherwhise there will be nasty side effects. Anyway, I am certain that it is possible to use `transitions` in your intented way but this requires some modifications that would introduce too many breaking changes in the package.
