### ISSUE TITLE
Transition behavior difference in HSM

### ISSUE THREAD

**Issue by matlom** [pytransitions/transitions#458]
If I run the example notebook `examples/Graph MIxin Demo Nested.ipynb` with the following states and transitions:

Python: 3.6.8
Transitions: 0.8.2

```python
states = [{'name': 'caffeinated', 'on_enter': 'do_x',
           'children':['dithering', 'running']},
          {'name': 'standing', 'on_enter': ['do_x', 'do_y'], 'on_exit': 'do_z'},
          {'name': 'walking', 'tags': ['accepted', 'pending'], 'timeout': 5, 'on_timeout': 'do_z'},
          
         ]
transitions = [
  ['walk', 'standing', 'walking'],
  ['go', 'standing', 'walking'],
  ['stop', 'walking', 'standing'],
  {'trigger': 'drink', 'source': '*', 'dest': 'caffeinated_dithering',
   'conditions':'is_hot', 'unless': 'is_too_hot'},
  ['walk', 'caffeinated_dithering', 'caffeinated_running'],
  ['relax', 'caffeinated', 'standing'],
  ['sip', 'standing', 'caffeinated'],
  ['drink', 'caffeinated_dithering', '=']
]
```

I get an exception (below) when following these two transitions: 

```python
model.drink()
model.drink()
```

The only difference to the example notebook is that I moved the transition `['drink', 'caffeinated_dithering', '=']` to the `transitions` instead of defining it in the state child `caffeinated`. I do not get this exception in version 0.7. 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-0b8549feb4ed> in <module>
----> 1 model.drink()

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in trigger_event(self, _model, _trigger, *args, **kwargs)
    696         """
    697         with self():
--> 698             res = self._trigger_event(_model, _trigger, None, *args, **kwargs)
    699         return self._check_event_result(res, _model, _trigger)
    700 

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in _trigger_event(self, _model, _trigger, _state_tree, *args, **kwargs)
    856                     res[key] = self._trigger_event(_model, _trigger, value, *args, **kwargs)
    857             if not res.get(key, None) and _trigger in self.events:
--> 858                 res[key] = self.events[_trigger].trigger(_model, self, *args, **kwargs)
    859         return None if not res or all(v is None for v in res.values()) else any(res.values())

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in trigger(self, _model, _machine, *args, **kwargs)
    110         # Machine._process should not be called somewhere else. That's why it should not be exposed
    111         # to Machine users.
--> 112         return _machine._process(func)
    113 
    114     def _trigger(self, _model, _machine, *args, **kwargs):

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/core.py in _process(self, trigger)
   1112             if not self._transition_queue:
   1113                 # if trigger raises an Error, it has to be handled by the Machine.process caller
-> 1114                 return trigger()
   1115             else:
   1116                 raise MachineError("Attempt to process events synchronously while transition queue is not empty!")

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in _trigger(self, _model, _machine, *args, **kwargs)
    125                 event_data.source_name = state_name
    126                 event_data.source_path = copy.copy(state_path)
--> 127                 res = self._process(event_data)
    128                 if res:
    129                     elems = state_path

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in _process(self, event_data)
    141             for trans in self.transitions[event_data.source_name]:
    142                 event_data.transition = trans
--> 143                 if trans.execute(event_data):
    144                     event_data.result = True
    145                     break

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/core.py in execute(self, event_data)
    267 
    268         if self.dest:  # if self.dest is None this is an internal transition with no actual state change
--> 269             self._change_state(event_data)
    270 
    271         event_data.machine.callbacks(itertools.chain(self.after, event_data.machine.after_state_change), event_data)

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/diagrams.py in _change_state(self, event_data)
     29         graph.reset_styling()
     30         graph.set_previous_transition(self.source, self.dest, event_data.event.name)
---> 31         _super(TransitionGraphSupport, self)._change_state(event_data)  # pylint: disable=protected-access
     32         for state in _flatten(listify(getattr(event_data.model, event_data.machine.model_attribute))):
     33             graph.set_node_style(self.dest if hasattr(state, 'name') else state, 'active')

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in _change_state(self, event_data)
    257 
    258     def _change_state(self, event_data):
--> 259         state_tree, exit_partials, enter_partials = self._resolve_transition(event_data)
    260         for func in exit_partials:
    261             func()

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in _resolve_transition(self, event_data)
    243                          for state_name in _resolve_order(scoped_tree)]
    244         if dst_name_path:
--> 245             new_states, enter_partials = self._enter_nested(root, dst_name_path, scope + root, event_data)
    246         else:
    247             new_states, enter_partials = {}, []

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in _enter_nested(self, root, dest, prefix_path, event_data)
    268             state_name = root.pop(0)
    269             with event_data.machine(state_name):
--> 270                 return self._enter_nested(root, dest, prefix_path, event_data)
    271         elif dest:
    272             new_states = OrderedDict()

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in _enter_nested(self, root, dest, prefix_path, event_data)
    272             new_states = OrderedDict()
    273             state_name = dest.pop(0)
--> 274             with event_data.machine(state_name):
    275                 new_states[state_name], new_enter = self._enter_nested([], dest, prefix_path + [state_name], event_data)
    276                 enter_partials = [partial(event_data.machine.scoped.scoped_enter, event_data, prefix_path)] + new_enter

~/dev/my_app/venv/lib/python3.6/site-packages/transitions/extensions/nesting.py in __call__(self, to_scope)
    338         if isinstance(to_scope, string_types):
    339             state_name = to_scope.split(self.state_cls.separator)[0]
--> 340             state = self.states[state_name]
    341             to_scope = (state, state.states, state.events)
    342         elif isinstance(to_scope, Enum):

KeyError: 'caffeinated'
```

**Comment by aleneum** [comment]
Hello @matlom,

I can confirm that this is a bug. Thank you for reporting that one. I am running the compatibility checks and will push the fix right away.
