### ISSUE TITLE
Serialize and deserialize the state machine to a dictionary

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions#483]
If I want to serialize and deserialize the state machine and its current state(s) we need a way to transform the `Machine` object to a dict and initialize a `Machine` from a dict.

**Comment by aleneum** [comment]
That's what `MarkupMachine` is doing. It's used for Graphviz and communication in the `transitions-gui` project. There is a small example in the [FAQs](https://github.com/pytransitions/transitions/blob/master/examples/Frequently%20asked%20questions.ipynb).

**Comment by thedrow** [comment]
I don't need Graphviz support. I need to be able to serialize into JSON or MessagePack.

**Comment by aleneum** [comment]
Did you check the FAQ?

**Comment by thedrow** [comment]
Yes, I just did.
Is there a way to mixin this class to the other variants?

**Comment by aleneum** [comment]
Since `GraphMachine` extends `MarkupMachine` (that's the only reason why I mentioned Graphviz) I'd say that you can combine `MarkupMachine` with all the other extensions. You can have a look at `factory.py` in `extensions` to see which combinations are currently tested.

**Comment by thedrow** [comment]
It's not clear from the README though.

**Comment by thedrow** [comment]
I'll close this for now.
