### ISSUE TITLE
get_transitions does not support enum sources or destinations

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions#491]
`get_transitions` currently assumes that the `source` and `dest` keyword arguments are strings.
I think they can be enums too.

**Comment by aleneum** [comment]
I added support for `Enum` and `State` in d1c18cd. Furthermore, `HierarchicalMachine.get_transitions` has a new keyword `delegate` (default value is `False`). If set to `True`, `get_transitions` will also return transitions from the parent of source.
