### ISSUE TITLE
Include Diagram in README Example

### ISSUE THREAD

**Issue by frakman1** [pytransitions/transitions#497]
> They say a good example is worth 100 pages of API documentation, a million directives, or a thousand words.

They also say:

> A picture is worth a thousand words

:) 

Please include a diagram for your superhero example state machine. Something that shows the state names and transition actions.

**Comment by aleneum** [comment]
Hello @frakman1,

I guess you are talking about this?

![batman_diagram](https://user-images.githubusercontent.com/205986/104932302-c2f24580-59a7-11eb-8963-5dce738b9305.png)

Will be added right away.
