### ISSUE TITLE
Nested initial states don't work when creating a HFSM from another HFSM

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions#510]
Clone this commit and run the tests: https://github.com/celery/jumpstarter/pull/27/commits/9e161d3e4aba570b5891fa31cf53f8272aa4a38d.
I have no idea what happened and in any case, I found a workaround but this should be investigated.

**Comment by aleneum** [comment]
[Here](https://github.com/celery/jumpstarter/commit/9e161d3e4aba570b5891fa31cf53f8272aa4a38d#diff-316e63a2501fd72aff3342f8c644dddca256adc190a4088d0f514e63748f187aR55) you inherit from `AsyncTransition` but `NestedAsyncTransition` is required to resolve nested features such as initial values.

**Comment by thedrow** [comment]
Indeed that is the problem.
Shouldn't we have a typecheck in place?
