### ISSUE TITLE
Migrating testing away from travis-ci.org

### ISSUE THREAD

**Issue by aleneum** [pytransitions/transitions#513]
Travis is moving resources from travis-ci.org (open source platform) to travis-ci.com (their 'pro' platform). It now takes hours for a 5 minute test to run on travis-ci.org. One option would be to migrate the repos to travis-ci.com. However, what I really liked about travis-ci.org was that is did not require many repository permissions to operate. Travis-ci.com wants the full package: full access to all repositories. Should we instead migrate to Github Actions? CircleCi? Any suggestions?

I'd prefer a CI service that does not want me to hand over full writing permissions when simple hooks should be enough.

**Comment by wtgee** [comment]
I've mostly moved to GHA out of convenience and have been mostly satisfied. The ability to store artifacts (e.g. log files) has been convenient.  I think `travis-ci.com` supports this in some fashion but Travis always annoyed me so much in little ways that I've had no regrets.

No strong technical motivation though.

**Comment by aleneum** [comment]
Hi @wtgee,

thank you for your feedback. I tried GHA and it seems to work quite well.
