### ISSUE TITLE
Test coverage for resolving enums when tehy are set as nested initial states

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions#516]
#506 requires tests which were missing.
I need to write them and issue a PR.

**Comment by aleneum** [comment]
In 9061011, I rewrote `HierarchicalMachine.add_states` slightly to set `NestedState.initial` to (a list of) `NestedState` or `Enum` instead of (a list of) state names. See the added test in the commit. This should cover your PR as well.
