### ISSUE TITLE
Python 3.10 compatibility

### ISSUE THREAD

**Issue by debalance** [pytransitions/transitions#559]
Hi,

please make transitions compatible with Python 3.10.
Currently, several tests are failing when using Python 3.10.

You can find more information at https://bugs.debian.org/1001479 and in [python-transitions_0.8.10-1_amd64.build.txt](https://github.com/pytransitions/transitions/files/7698568/python-transitions_0.8.10-1_amd64.build.txt).

**Comment by debalance** [comment]
Hey @aleneum, latest git master builds + works fine, please make the release :)

**Comment by enjoysmath** [comment]
I just want to say what fucking bullshit this is.  I got Python 3.10 working with everything I need.  Python-statemachine really sucks and can't do what I need it to.  The only other option that produces diagrams is this library, and low and fucking behold it passes all 3.0+ tests but doesn't even install with pip...

I'll write my own god damn FSM library.
