### ISSUE TITLE
Error if pygraphviz is not installed

### ISSUE THREAD

**Issue by FridjofAmundsen** [pytransitions/transitions#569]
**graphviz is not used as fallback**
if pygraphviz is not available, an error is thrown. 
In Version 8.1 'graphviz' was used as a fallback.

**Minimal working example**

```python
from transitions.extensions import GraphMachine
class Model:
    pass
machine = GraphMachine(model=Model())
```

**Expected behavior**
I expect that in this case graphviz is used as a fallback.

**workaround**
```python
import pkgutil
from transitions.extensions import GraphMachine

class Model:
    pass
has_pygraphviz = pkgutil.find_loader('pygraphviz')
machine = GraphMachine(model=Model(),  use_pygraphviz=has_pygraphviz )
```

**Additional context**
the following patch would solve this issue.
[fallback_to_graphviz_patch.zip](https://github.com/pytransitions/transitions/files/8395593/fallback_to_graphviz_patch.zip)

**Comment by aleneum** [comment]
Hello @FridjofAmundsen,

thanks for the report and sorry for the regression. I will have a look whether we can easily integrate this as a test case.

**Comment by FridjofAmundsen** [comment]
@aleneum thanks. You don't have to apologize. I’m really happy that you put so much effort into this project.
