### ISSUE TITLE
Mermaid diagrams

### ISSUE THREAD

**Issue by ylhan** [pytransitions/transitions#611]
**Is your feature request related to a problem? Please describe.**
The current diagramming tool is great and generates cool looking images but they cannot be embedded natively in Github README's.

**Describe the solution you'd like**
Add mermaid as an output option to the diagramming tool. This will generate a high fidelity, interactive diagram that can be embedded natively in README's on Github. 
**Additional context**
[Example](https://gist.github.com/martinwoodward/8ad6296118c975510766d80310db71fd) mermaid diagram on github

**Comment by aleneum** [comment]
You already have :). I will close this issue when mermaid support hits the main branch and post updates here about testing branches or mermaid issues. So GitHub will let you know in any case.

**Comment by Ben-Taarit** [comment]
Any news on this one?
