### ISSUE TITLE
get_triggers does not work

### ISSUE THREAD

**Issue by jonra1993** [pytransitions/transitions#631]
**Describe the bug**
Thanks for creating this package. I am starting to use it and I am looking for a way to detect if there is an initial or end state. I found in your documentation the get_triggers function but does not work as expected. 
**Minimal working example**

```python
class Matter(object):
    def say_hello(self): print("hello, new state!")
    def say_goodbye(self): print("goodbye, old state!")

lump = Matter()

transitions = [
    { 'trigger': 'melt', 'source': 'solid', 'dest': 'liquid' },
    { 'trigger': 'evaporate', 'source': 'liquid', 'dest': 'gas' },
    { 'trigger': 'sublimate', 'source': 'solid', 'dest': 'gas' },
    { 'trigger': 'ionize', 'source': 'gas', 'dest': 'plasma' }
]


states = ['solid', 'liquid', 'gas', 'plasma']
m = Machine(lump, states, initial='liquid', transitions=transitions)
m.get_triggers('plasma')
```

**Expected behavior**
The output on the trigger should be an empty list because it is the last state it always shows the same no matter which state you use.

<img width="868" alt="image" src="https://github.com/pytransitions/transitions/assets/23468720/c3134dca-9046-4b97-8d0d-a4baa0ae584e">

**Additional context**
This is the current output
<img width="815" alt="image" src="https://github.com/pytransitions/transitions/assets/23468720/9f9b433f-7530-4a8c-8e4e-a5ce0a6a2101">

**Comment by aleneum** [comment]
Hello @jonra1993,

triggers are only available on the source state. In your code example:

```
transitions = [
    { 'trigger': 'melt', 'source': 'solid', 'dest': 'liquid' },
    { 'trigger': 'evaporate', 'source': 'liquid', 'dest': 'gas' },
    { 'trigger': 'sublimate', 'source': 'solid', 'dest': 'gas' },
    { 'trigger': 'ionize', 'source': 'gas', 'dest': 'plasma' }
]
``` 

you can trigger "melt" from state "solid", "evaporate" from "liquid" and so on. Consequently, "melt" is not a trigger for "solid" since it cannot be triggered when in that state.  As far as I can tell, "plasma" is not a source state for any of your transitions. Except auto transitions "to_<state>" there are no valid triggers. When you query triggers for "solid", you get "melt" and "sublimate":

```python
from transitions import Machine

class Matter(object):
    def say_hello(self): print("hello, new state!")
    def say_goodbye(self): print("goodbye, old state!")

lump = Matter()

transitions = [
    { 'trigger': 'melt', 'source': 'solid', 'dest': 'liquid' },
    { 'trigger': 'evaporate', 'source': 'liquid', 'dest': 'gas' },
    { 'trigger': 'sublimate', 'source': 'solid', 'dest': 'gas' },
    { 'trigger': 'ionize', 'source': 'gas', 'dest': 'plasma' }
]


states = ['solid', 'liquid', 'gas', 'plasma']
m = Machine(lump, states, initial='liquid', transitions=transitions)
print(m.get_triggers('solid'))
# >>> ['to_solid', 'to_liquid', 'to_gas', 'to_plasma', 'melt', 'sublimate']
```

**Comment by aleneum** [comment]
If it is the auto transitions that confuse you, you can disable them by passing "auto_transitions=False" to the constructor:

```python
from transitions import Machine

class Matter(object):
    def say_hello(self): print("hello, new state!")
    def say_goodbye(self): print("goodbye, old state!")

lump = Matter()

transitions = [
    { 'trigger': 'melt', 'source': 'solid', 'dest': 'liquid' },
    { 'trigger': 'evaporate', 'source': 'liquid', 'dest': 'gas' },
    { 'trigger': 'sublimate', 'source': 'solid', 'dest': 'gas' },
    { 'trigger': 'ionize', 'source': 'gas', 'dest': 'plasma' }
]


states = ['solid', 'liquid', 'gas', 'plasma']
m = Machine(lump, states, initial='liquid', transitions=transitions, auto_transitions=False)
print(m.get_triggers('plasma'))
```

They are enabled by default and are valid triggers. That's why `get_triggers` will return them when they are enabled.

**Comment by jonra1993** [comment]
Hello @aleneum after use `auto_transitions=False` it worked as I expected thanks for your help
