### ISSUE TITLE
after_state_change not triggered by set_state

### ISSUE THREAD

**Issue by louisjmorgan** [pytransitions/transitions#638]
**Describe the bug**

The after_state_change callback seems to only be triggered by transitions, and not by manually setting the state. This can't be feature, so I can only assume it's a bug.

**Minimal working example**

```python
def info():
    print("changed")


machine = Machine(
    states=["initial", "test"],
    transitions=[["test", "initial", "test"]],
    initial="initial",
    after_state_change=info)

machine.test()  # prints "changed"
print(machine.state)
machine.set_state("initial")  # doesn't print changed
print(machine.state)

```

output:

```
changed
test
initial

```

**Expected behavior**

I expect changing the state to trigger the `after_state_change` callback, because the state has changed.

**Comment by aleneum** [comment]
Hi @louisjmorgan,

as of now, this is expected behaviour. `set_state` just simply assigns a state to  a model but does not trigger any callbacks. You could use the default auto transitions which more or less have the same effect but process state-related callbacks such as `after_state_change `.

```python
# instead of machine.set_state("initial")
machine.to_initial()
```

**Comment by louisjmorgan** [comment]
Fair enough. I think `after_state_change` should be called something else in that case, but I understand.
