### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by folt** [pytransitions/transitions#651]
The last release was Release 0.9.0 Sep 2, 2022
Maybe it makes sense to update the version of the library and include recent improvements in the release?

**Comment by folt** [comment]
What do you think about it  @aleneum ?

**Comment by aleneum** [comment]
Hi @folt,

you are absolutely right. There are some lose ends that need to be tackled before the next release though. The mermaid.js support is looooong overdue. I haven't worked on `transitions` for a while but will make it a priority again. I'll keep you posted.

**Comment by folt** [comment]
Perhaps I could help?

**Comment by aleneum** [comment]
Hello @folt,

thank you for the offer. I'll let you know if there is something I need help with.

Best regards!

**Comment by aleneum** [comment]
Hi @folt,

just wanted to let you know I pushed 0.9.1 to PyPI.
